### ISSUE TITLE
Solver timeout interface

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#1015]
Manticore should have an interface for controlling the timeout used when submitting solver queries. This is distinct from manticore's overall timeout.

Right now, it's hardcoded in solver.py with the `-t` flag.

https://github.com/trailofbits/manticore/blob/90fdbb8753daf8aa84a22ef3789fe3933733ca51/manticore/core/smtlib/solver.py#L150

For my particular use case an API would be fine, but we should probably also expose a cli flag for it. Need some brainstorming on what kind of API.

**Comment by feliam** [comment]
Related https://github.com/trailofbits/manticore/issues/372

Need a global config module that is backed by:
* defaults
* .ini file that will end up in the workspace for reproducibility(that could be a cli argument)
* commandline arguments

**Comment by mossberg** [comment]
for the moment, even any kind of cli/api would be good though, doesn't need to involve a full blown config thing just yet.

**Comment by EricR** [comment]
It looks like https://github.com/trailofbits/manticore/pull/1139 resolved this. Can this be closed?
