### ISSUE TITLE
Optimize event publishing

### ISSUE THREAD

**Issue by offlinemark** [trailofbits/manticore#1050]
Currently, no particular effort has been used to optimize the event publishing interface `Eventful._publish`. One common request is to make manticore faster, and this would be a key optimization point to look into. Events are published in many critical places within manticore, including tight loops, and the current implementation can be optimized in many ways to make the overhead of publishing events, especially events who have no registered handlers, faster.

**Comment by mossberg** [comment]
As a related task to this, it might be appropriate to do a small audit of all the events that are actually emitted and remove any of the ones that are not really useful, or extremely rarely used. However, if we can optimize publishing to be nearly a nop or negligible overhead if there are no handlers, this is probably not necessary.

**Comment by feliam** [comment]
+1 to make publishing lazy and see.

**Comment by mossberg** [comment]
what do you mean by lazy exactly?

**Comment by ehennenfent** [comment]
#1388
