### ISSUE TITLE
EVM. Split gas consumption from instruction handler

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#1074]
Research. Check factibility.
Separate the fee calculation from the body of the instruction handler so we can add constraints about it and then concretize the arguments with gas related constraints in the path. Specially interesting for operations that have memory/storage accesses
```
arguments = top_arguments_for_instruction()
if not concretizing: #check that we are not doing it twice
   fee = calculate_fee(arguments)
   -do gas exceptions as configured of ignore-
handle_instruction(arguments) #potentially raising ConcretizeStack
```

**Comment by disconnect3d** [comment]
This has been added in https://github.com/trailofbits/manticore/pull/1279 so I am closing it.
