### ISSUE TITLE
Specific targetting in symbolic file input

### ISSUE THREAD

**Issue by caballomaldito** [trailofbits/manticore#1135]
### OS / Environment
Ubuntu 18.04 LTS

### Manticore version
Version: 0.2.1.1

### Python version
Python 3.6.5

### Dependencies
apturl==0.5.2
asn1crypto==0.24.0
Brlapi==0.6.6
capstone==3.0.5
certifi==2018.1.18
chardet==3.0.4
command-not-found==0.3
cryptography==2.1.4
cupshelpers==1.0
defer==1.0.6
distro-info==0.18
future==0.16.0
httplib2==0.9.2
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
manticore==0.2.1.1
MarkupSafe==1.0
oauth==1.0.1
olefile==0.45.1
pexpect==4.2.1
Pillow==5.1.0
ply==3.11
protobuf==3.0.0
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pyelftools==0.25
pyevmasm==0.1.1
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyRFC3339==1.0
pysha3==1.0.2
python-apt==1.6.0
python-debian==0.1.32
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
simplejson==3.13.2
six==1.11.0
system-service==0.3
systemd-python==234
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unicorn==1.0.1
urllib3==1.22
usb-creator==0.3.3
wadllib==1.3.2
xkit==0.0.0
z3-solver==4.8.0.0.post1
zope.interface==4.3.2

### Summary of the problem
I'm using the following command in order to find vulnerabilities in the file parser, however is reaching to path explosion due a large size and complex structure.

manticore ./binary --file my_symbolic_file1.txt

I was wondering at the API level, how could I specify which parts, functions, or sequences of bytes of the 'seed' file can be taken as a reference instead of the whole 'seed' file, on the other hand, I would also like to know if it is possible narrow the concolic execution to further reduce the path explosion problem.

Could you provide a basic example?

Thank you very much!

### Expected behavior
Binary analyzed

### Actual behavior
The process never ends due path explosion and large size and complex structure of binary

**Comment by mossberg** [comment]
hi! thanks for trying manticore :)

in my_symbolic_file.txt you can mix regular bytes and symbolic bytes. `+` is the special character telling manticore to make that byte symbolic. i would recommend starting first with a fully concrete input file, and slowly adding symbolic bytes into it using the `+` character.

also, you might try hooking certain PCs you don't care about and using `state.abandon()`.

take a look here if you haven't already too: https://github.com/trailofbits/manticore/wiki/Optimization-Tips

**Comment by disconnect3d** [comment]
I believe the new link for optimization binary analysis is https://github.com/trailofbits/manticore/wiki/Analysis-Tips#binary-analysis

Anyway, there is no silver bullet to win path explosion so it is best to abandon the states you don't need or hack the binary to jump to the part of code that is interesting to you.

Of course, there are some improvements that can be implemented like optimizing Manticore or distributing it to many machines and hopefully we will get to that someday.

I believe there is not much more we can do about this issue so I am closing it.
