### ISSUE TITLE
Cloud integration

### ISSUE THREAD

**Issue by offlinemark** [trailofbits/manticore#1136]
idea: make it really easy to run manticore on a beefy cloud machine (for the long run scenario), without having to manually bring up the machine yourself. algo style!

**Comment by ehennenfent** [comment]
Closing this as we've got a prototype in the [cloudify](https://github.com/trailofbits/manticore/tree/cloudify) branch already, and should soon have our intern's version ([pwang00/Ansible-Manticore](https://github.com/pwang00/Ansible-Manticore)) integrated as well
