### ISSUE TITLE
Colored detector output

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#1158]
To make the findings stand out, we could add colored output.

![image](https://user-images.githubusercontent.com/2467355/46235937-8cadd980-c34a-11e8-9621-36c1dd6b4704.png)

**Comment by redyoshi49q** [comment]
I have a few questions relating to this issue request:

-  Should color support be given a command line parameter?  Should it default to on or off?
-  Should support for 16 colors be assumed or tested for?  Is there a preferred method for testing for such support?
-  Is it safe to assume that there's no need to consider using 256 color or "true color" for this purpose, or is the want for a larger and more diverse color palette sufficient to use 256 color support if it exists (with 16 color and no color as fallbacks)?
-  Is there an output environment that should be assumed, or should the environment that Manticore is outputting to be tested for?  In my experience, color codes in a .bashrc can react differently in a virtual terminal, a terminal emulator, an Emacs shell, and an Emacs term.

**Comment by mossberg** [comment]
> * Should color support be given a command line parameter?  Should it default to on or off?

i think it should probably default to on, with ability to disable



> * Should support for 16 colors be assumed or tested for?  Is there a preferred method for testing for such support?

i don't have a preferred method. i'd say we can probably assume support exists. we can probably assume a fairly regular ubuntu 18.04 ish setup, we explicitly recommend that in the readme.





> * Is it safe to assume that there's no need to consider using 256 color or "true color" for this purpose

yeah, probably safe for now.

in general, i don't think we need to implement the most incredibly robust solution right now. let's just do something simple that works "most of the time"?

**Comment by dguido** [comment]
Closed in #1177
