### ISSUE TITLE
Missing EVMWorld.last_return_data

### ISSUE THREAD

**Issue by montyly** [trailofbits/manticore#1170]
### Manticore version
98b9d360a92c8f4acf75c7e6327e295b3a8a7d0d

### Summary of the problem

https://github.com/trailofbits/manticore/blob/98b9d360a92c8f4acf75c7e6327e295b3a8a7d0d/manticore/ethereum/__init__.py#L606-L609

`last_return_data` does not exist anymore in `EVMWorld`

`last_return` should return `state.platform.transactions[-1].return_data`, or `last_return_data` should be re-added to `EVMWorld`

**Comment by disconnect3d** [comment]
This has been fixed in https://github.com/trailofbits/manticore/pull/1341/files
I hope this is the proper fix.

@feliam can you double check it?
