### ISSUE TITLE
Check call signature counts in an manticore.ethereum.EVMContract call ? 

### ISSUE THREAD

**Issue by rocky** [trailofbits/manticore#1178]
### OS / Environment

macOS High Sierra
### Manticore version

Version: 0.2.1.1

### Python version

Python 3.3.6
### Summary of the problem

When a Solidity function is called in a `manticore.ethereum.EVMContract` object, the parameter count of the function is not checked. 
### Step to reproduce the behavior

This contract from the  trufflecon2018 manticore example: 

```solidity
pragma solidity^0.4.24;
contract Overflow {
    uint public sellerBalance=0;

    function add(uint value) public returns (bool){
        sellerBalance += value; // complicated math, possible overflow
    }
}
```

Now here is an improper use of the call `add`, since there are two parameters

```python
from manticore.ethereum import ManticoreEVM
m = ManticoreEVM()
with open('overflow.sol') as f: source_code = f.read()
user_account = m.create_account(balance=1000)
contract_account = m.solidity_create_contract(source_code,  owner=user_account)
symbolic_var1 = m.make_symbolic_value()
symbolic_var2 = m.make_symbolic_value()
contract_account.add(symbolic_var1, symbolic_var2)  # Uses one parameter, not two!
```

### Expected behavior

Some sort of error in calling `add()` which takes only one parameter
### Actual behavior

No error.

**Comment by mossberg** [comment]
thanks rocky :) pr 1181 should address this; it causes a warning to be logged if this situation happens

```
[I] (py3) vagrant ubuntu-bionic /v/m/1178 ❯ py x.py
2018-10-08 17:42:25,937: [5544] m.e.abi:WARNING: Number of provided arguments (2) does not match number of arguments in signature: add(uint256)

```

**Comment by rocky** [comment]
That was quick! Thanks!
