### ISSUE TITLE
FilterFunctions.will_open_transaction_callback tries to match fallback function hash with string instead of a bytes array

### ISSUE THREAD

**Issue by stephan-tolksdorf** [trailofbits/manticore#1196]
The master branch version of `Ethereum.FilterFunctions.will_open_transaction_callback` [uses the string `'00000000'`](https://github.com/trailofbits/manticore/blob/master/manticore/ethereum/__init__.py#L103) instead of b'\0\0\0\0' for matching the fallback function hash, which leads to faulty behaviour.

Should I submit a pull request to fix this issue? Should the PR include a test?

**Comment by disconnect3d** [comment]
@stephan-tolksdorf Hey, thanks for the issue.

> Should I submit a pull request to fix this issue? Should the PR include a test?

Yes, please! :)

**Comment by dguido** [comment]
This appears fixed. Close it?
