### ISSUE TITLE
solidity_create_contract may create contract with wrong constructor argument values

### ISSUE THREAD

**Issue by stephan-tolksdorf** [trailofbits/manticore#1209]
`SolidityMetadata.__init__` does not properly handle the case where multiple ABI items have no name, which happens when the contract has both a constructor and an explicitly defined fallback function. In that case the fallback function metadata will override the constructor metadata. This causes `get_constructor_arguments()` to return `'()'` irrespective of the actual constructor parameters. If the contract constructor actually has parameters, this leads `ManticoreEVM.solidity_create_contract` to pass the wrong type signature to `ABI.serialize`. Since `ABI._serialize_tuple` does not check the length of its argument tuples, `ABI.serialize` will not report an error and return without serializing any arguments. This leads to the transaction data missing the constructor arguments data, which has the same effect as if all arguments were zero. (If no `args` are passed to `solidity_create_contract`, symbolic arguments will be created according to the wrong, empty tuple signature. In that case the tuples passed to `ABI.serialize` have the same 0 length, but the end result is still the same.)

I'll submit a PR that fixes the constructor and fallback function handling in `SolidityMetadata.__init__` and also adds a tuple length check to `ABI._serialize_tuple`.

`SolidityMetadata` currently also doesn't properly handle overloaded functions, but fixing that requires an API change to the `abi` property. I'll open a separate issue for that.

**Comment by stephan-tolksdorf** [comment]
@mossberg  This bug was also fixed by PR #1212

**Comment by mossberg** [comment]
thanks!
