### ISSUE TITLE
SolidityMetadata doesn't import the ABI data for overloaded functions properly

### ISSUE THREAD

**Issue by stephan-tolksdorf** [trailofbits/manticore#1210]
The `abi` property of `SolidityMetadata` is currently a 1-1 mapping from the function name to the Solidity ABI metadata, even though functions can be overloaded (i.e. there can be multiple functions with the same name and different parameter lists). If the contract contains overloaded functions, only one function from each overload set will be represented in the `abi` dict. In that case  `get_abi`, `get_func_argument_types` and `get_func_return_types` may return wrong results.

The `abi` property currently will also store items for event declarations, which can be overloaded too.

The `abi` property seems to be part of the public API, though at least within the Manticore project it doesn't seem to be used outside the class.

I'll submit a PR with a proposed fix.

**Comment by disconnect3d** [comment]
Can you show a minimal working example when the functions return wrong results?

**Comment by stephan-tolksdorf** [comment]
This is one example case where the functions return the wrong result:

        m = ManticoreEVM()
        source_code = '''
        contract C {
            function f() public {}
            function f(uint a) public payable {}
        }
        '''
        user_account = m.create_account(balance=1000, name='user_account')
        contract_account = m.solidity_create_contract(source_code, owner=user_account, name='contract_account')
        md = m.get_metadata(contract_account)
        sel1 = ABI.function_selector('f()')
        sel2 = ABI.function_selector('f(uint256)')
        assert(sel1 != sel2)
        abi1 = md.get_abi(ABI.function_selector('f()')) # Actually returns the abi for f(uint256).
        abi2 = md.get_abi(ABI.function_selector('f(uint256)'))
        assert(abi1['type'] == 'function')
        assert(abi2['type'] == 'function')
        assert(abi1 != abi2) # This assert fails.

Note that overloaded functions aren't the only problem that the PR fixes. Currently the implementation e.g. also mistakes event items for function items.

Note that the PR for this issue builds on my previous PR for the related issue #1209. The PR for that issue contains a test case where without the PR a contract with the wrong data is constructed.

**Comment by mossberg** [comment]
addressed #1212
