### ISSUE TITLE
Feasible state found if value (in .transaction) is set to 0 but not if using a symbolic value

### ISSUE THREAD

**Issue by ralph-pichler** [trailofbits/manticore#1237]
### OS / Environment

MacOS 10.14

### Manticore version

Version: 0.2.2

### Python version

Python 3.7.0

### Dependencies

asn1crypto==0.24.0
attrdict==2.0.0
capstone==3.0.5.post1
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
coincurve==9.0.0
configparser==3.5.0
coverage==4.5.1
cytoolz==0.9.0.1
dictionaries==0.0.1
eth-abi==1.2.2
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b33
eth-typing==1.3.0
eth-utils==1.2.2
ethereum==2.3.2
future==0.16.0
hexbytes==0.1.0
idna==2.7
Jinja2==2.10
manticore==0.2.2
MarkupSafe==1.0
mock==2.0.0
mythril==0.18.12
parsimonious==0.8.1
pbkdf2==1.3
pbr==5.0.0
persistent==4.4.2
ply==3.11
plyvel==1.0.5
py-ecc==1.4.3
py-flags==1.1.2
py-solc==3.2.0
pycairo==1.17.1
pycparser==2.19
pycryptodome==3.6.6
pyelftools==0.25
pyethash==0.1.27
pyevmasm==0.1.0
PyGObject==3.30.1
pysha3==1.0.2
PyYAML==3.13
repoze.lru==0.7
requests==2.20.0
rlp==1.0.3
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
transaction==2.3.0
unicorn==1.0.1
urllib3==1.24
z3-solver==4.8.0.0
zope.interface==4.5.0

### Summary of the problem

A feasible state is found if value in .transaction is 0 but not if value is a symbolic value

### Step to reproduce the behavior

The contract is from the DEVCON4 workshop:
```solidity
pragma solidity ^0.4.24;
contract UnprotectedWallet{
    address public owner;

    modifier onlyowner {
        require(msg.sender==owner);
        _;
    }

    constructor() public {
        owner = msg.sender;
    }
    function changeOwner(address _newOwner) public {
       owner = _newOwner;
    }

    function deposit() payable public { 
    }

    function withdraw() onlyowner public {
        msg.sender.transfer(this.balance);
    }
}
```

This is the script used
```python
from manticore.ethereum import ManticoreEVM, ABI
from manticore.core.smtlib import Operators, solver

###### Initialization ######

m = ManticoreEVM()
with open('unprotected.sol') as f:
    source_code = f.read()

creator_account = m.create_account(balance=10)
attack_account = m.create_account(balance=0)

contract_account = m.solidity_create_contract(source_code, owner=creator_account, balance=0)

###### Exploration ######

contract_account.deposit(caller=creator_account, value=1)

value1 = m.make_symbolic_value()
data1 = m.make_symbolic_buffer(640)

m.transaction(caller=attack_account, address=contract_account, data=data1, value=value1)

value2 = m.make_symbolic_value()
data2 = m.make_symbolic_buffer(640)

m.transaction(caller=attack_account, address=contract_account, data=data2, value=value2)

bug_found = False

for state in m.all_states:
	attack_balance = state.platform.get_balance(attack_account.address)
	state.constrain(attack_balance == 1)
	if state.is_feasible():
		print("Bug found! see {}".format(m.workspace))
		m.generate_testcase(state, 'Bug')
		bug_found = True

if not bug_found:
    print('No bug were found')
```

This is the same script except using a hardcoded 0 instead of the symbolic value.
```python
from manticore.ethereum import ManticoreEVM, ABI
from manticore.core.smtlib import Operators, solver

###### Initialization ######

m = ManticoreEVM()
with open('unprotected.sol') as f:
    source_code = f.read()

creator_account = m.create_account(balance=10)
attack_account = m.create_account(balance=0)

contract_account = m.solidity_create_contract(source_code, owner=creator_account, balance=0)

###### Exploration ######

contract_account.deposit(caller=creator_account, value=1)

value1 = m.make_symbolic_value()
data1 = m.make_symbolic_buffer(640)

m.transaction(caller=attack_account, address=contract_account, data=data1, value=0)

value2 = m.make_symbolic_value()
data2 = m.make_symbolic_buffer(640)

m.transaction(caller=attack_account, address=contract_account, data=data2, value=0)

bug_found = False

for state in m.all_states:
	attack_balance = state.platform.get_balance(attack_account.address)
	state.constrain(attack_balance == 1)
	if state.is_feasible():
		print("Bug found! see {}".format(m.workspace))
		m.generate_testcase(state, 'Bug')
		bug_found = True

if not bug_found:
    print('No bug were found')
```

### Expected behavior

In both scripts it should find a bug (since it works with 0 and the symbolic value should also include the possibility of 0)

### Actual behavior

With 0 a bug is found, with the symbolic value it is not

**Comment by stephan-tolksdorf** [comment]
This is a bug in [`EVM.transact._pre_func`](https://github.com/trailofbits/manticore/blob/220a481bbeeb58c640316131db819dbb559ae828/manticore/platforms/evm.py#L434), which sets the `_on_transaction` flag even if the `_pre` function raises a non-`StartTx` exception. In the above test case a `ConcretizeStack` exception is thrown when the `CALL` for `msg.sender.transfer(this.balance)` is executed .

I will prepare pull request with a fix.

**Comment by feliam** [comment]
WoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooW!
