### ISSUE TITLE
Make mcore installable for specific targets

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#1247]
* Work out setup.py so it is possible to install EVM(or other arch) only manticore.
* Fix and refactor imports so manticore does not need to have say Unicorn when in EVM mode 
* `pip install manticore .[intel]` will install manticore for x86/amd64 stuff
* `pip install manticore .[eth]` if they want ethereum stuff
* `pip install manticore .[decree]` if they want decree stuff
* `pip install manticore .[intel, eth]` should install intel and ethereum stuff (not sure about the syntax here)
* `pip install manticore .` should install all of it  (if possible
* similar behavior should be doable via `python setup.py ..`

...

**Comment by mossberg** [comment]
proposed solution for this is to invert the defaults and have `pip install manticore` only install evm deps. in the setup.py `install_requires` will have the basic things for evm to work. then if a user desires binary analysis deps, they can do `manticore[native]`, which will use `extras_require` to install capstone, unicorn, pyelftool, etc.

**Comment by disconnect3d** [comment]
In the end we decided to make it like this (merged in #1257 ):

* `pip install manticore` - installs core and ethereum dependencies
* `pip install manticore[native]` - installs core, ethereum and native dependencies

as rather most of our users use Manticore for ethereum related stuff and ethereum dependencies can be installed without compiling additional modules.
