### ISSUE TITLE
Rename detectors to agree with Slither

### ISSUE THREAD

**Issue by dguido** [trailofbits/manticore#1252]
[Manticore's detectors](https://github.com/trailofbits/manticore/wiki/Ethereum-Detectors) should work the same on the CLI, be named the same, and have the same severity levels (if any are reported) as [Slither](https://github.com/trailofbits/slither#detectors).

**Comment by disconnect3d** [comment]
Note to self: after merging #1286 update https://github.com/trailofbits/manticore/wiki/Ethereum-Detectors
