### ISSUE TITLE
Reduce the number of outstanding branches

### ISSUE THREAD

**Issue by dguido** [trailofbits/manticore#1258]
Let's review the state of our outstanding branches. Are there any that we want to merge right away or throw out right away? Do any require extended discussion?

**Comment by disconnect3d** [comment]
https://github.com/trailofbits/manticore/branches

**Comment by dguido** [comment]
Poke

**Comment by ehennenfent** [comment]
Just did another purge of the stale branches, so let's close this issue. I uploaded a backup of the full repository to Google Drive prior to deleting, so they're still available if we need them.
