### ISSUE TITLE
Running manticore throws error

### ISSUE THREAD

**Issue by ArinCantCode** [trailofbits/manticore#1296]
### OS / Environment
 Ubuntu GLIBC 2.23-0ubuntu10 2.23

### Manticore version
Metadata-Version: 2.0
Version: 0.2.2

### Python version

python3 --version: Python 3.5.2
python --version: Python 2.7.12

### Dependencies
blinker==1.3
capstone==3.0.5.post1
chardet==2.3.0
cloud-init==18.4
command-not-found==0.3
configobj==5.0.6
cryptography==1.2.3
future==0.17.1
idna==2.0
Jinja2==2.8
jsonpatch==1.10
jsonpointer==1.9
language-selector==0.1
manticore==0.2.2
MarkupSafe==0.23
oauthlib==1.0.3
pbr==5.1.1
ply==3.11
prettytable==0.7.2
pyasn1==0.1.9
pycurl==7.43.0
pyelftools==0.25
pyevmasm==0.1.0
pygobject==3.20.0
PyJWT==1.3.0
pyserial==3.0.1
pysha3==1.0.2
python-apt==1.1.0b1+ubuntu0
python-debian==0.1.27
python-systemd==231
PyYAML==3.13
requests==2.9.1
six==1.10.0
ssh-import-id==5.5
stevedore==1.30.0
ufw==0.35
unattended-upgrades==0.1
unicorn==1.0.1
urllib3==1.13.1
virtualenv==16.1.0
virtualenv-clone==0.4.0
virtualenvwrapper==4.8.2
z3-solver==4.8.0.0.post1

### Summary of the problem
any attempt of running manticore throws errors that i put below in "any relevant logs" section

### Step to reproduce the behavior
trying to run manticore

### Any relevant logs

Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 9, in <module>
    load_entry_point('manticore==0.2.2', 'console_scripts', 'manticore')()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/home/arin/.local/lib/python3.5/site-packages/manticore/__init__.py", line 1, in <module>
    from .manticore import Manticore, STDIN_INPUT_DEFAULT_SIZE  # noqa

  File "/home/arin/.local/lib/python3.5/site-packages/manticore/manticore.py", line 48
    logger.info(f'Starting with concrete input: {concrete_start}')
                                                            
SyntaxError: invalid syntax

**Comment by mossberg** [comment]
thanks @ArinCantCode ! it looks like your stack trace is a little chopped off on the right, could you post a full one?

**Comment by ArinCantCode** [comment]
@mossberg oops sorry missed that, updated.

**Comment by disconnect3d** [comment]
@ArinCantCode 
Hey,

The problem lies in:

> python3 --version: Python 3.5.2

As our documentation states:

> Note: Beginning with version 0.2.0, Python 3.6+ is required.

So it is the [f-string interpolation added with Python 3.6](https://www.python.org/dev/peps/pep-0498/) that causes the `SyntaxError` at your end.

Please update your Python version OR use multiple Python versions (see PyEnv for that) OR use Manticore in a Docker container (we have our own `trailofbits/manticore` docker image).
