### ISSUE TITLE
EVM Contract creation fails silently at solidity_create_contract

### ISSUE THREAD

**Issue by perks** [trailofbits/manticore#1297]
### Summary of the problem

Instantiating a contract using `solidity_create_contract` fails silently (returns None) when adding a `balance` parameter. 

### Step to reproduce the behavior

Using the `.sol` code provided in the Devcon 4 Manticore workshop:
https://github.com/trailofbits/publications/blob/master/workshops/Using%20Manticore%20and%20Symbolic%20Execution%20to%20Find%20Smart%20Contracts%20Bugs%20-%20Devcon%204/exercises/unprotected.sol

Setup:

```python
from manticore.ethereum import ManticoreEVM

m = ManticoreEVM() # initiate the blockchain
with open('unprotected.sol') as f:
    source_code = f.read()

# Generate the accounts. Creator has 10 ethers; attacker 0 
creator_account = m.create_account(balance=10*10**18)
attacker_account = m.create_account(balance=0)
```
Passes:
```python3
contract_account = m.solidity_create_contract(source_code, owner=creator_account)
```
Fails:
```python3
contract_account = m.solidity_create_contract(source_code, owner=creator_account, balance=10**18)
```

In particular the thing that causes the return:
https://github.com/trailofbits/manticore/blob/e8a6321707e36e998b4f6adc8f9675affdf16112/manticore/ethereum/manticore.py#L613-L614

**Comment by mossberg** [comment]
thanks @perks !

**Comment by disconnect3d** [comment]
A minimal not-working example:
```python
from manticore.ethereum.plugins import VerboseTrace
from manticore.ethereum import ManticoreEVM

m = ManticoreEVM() # initiate the blockchain

m.register_plugin(VerboseTrace())

ManticoreEVM.verbosity(2)

source_code = '''
pragma solidity ^0.4.24;
contract UnprotectedWallet {
    address public owner;

    modifier onlyowner {
        require(msg.sender==owner);
        _;
    }

    constructor() public {
        owner = msg.sender;
    }
    function changeOwner(address _newOwner) public {
       owner = _newOwner;
    }

    function deposit() payable public { 
    }

    function withdraw() onlyowner public {
        msg.sender.transfer(this.balance);
    }
}
'''


# Generate the accounts. Creator has 10 ethers; attacker 0 
creator_account = m.create_account(balance=10*10**18)
attacker_account = m.create_account(balance=0)

# This DOES NOT return `None` and is okay
# contract_account1 = m.solidity_create_contract(source_code, owner=creator_account)

# This SHOULD NOT return `None`
contract_account2 = m.solidity_create_contract(source_code, owner=creator_account, balance=10**18)

print(m.workspace)

m.finalize()
```
Note that I register the `VerboseTrace` plugin which has been fixed recently, so please use master branch for that.

It seems that the issue lies somewhere during contract constructor execution.

**Comment by disconnect3d** [comment]
Diff between two states (made via `vimdiff mcore_*/*.trace`, the `*.verbose_trace` diff can also be helpful to understand what's going on):
![image](https://user-images.githubusercontent.com/10009354/50129375-edc5b900-0278-11e9-990e-84182b4af25e.png)

Long story short: *if the contract's constructor is not payable, sending ether to it causes it to REVERT.* Because of that, since there are no states left, we return `None`.

**Comment by disconnect3d** [comment]
This issue has been addressed in https://github.com/trailofbits/manticore/pull/1311.
