### ISSUE TITLE
Fix ARMv7 dynamic binary errors

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#131]
When a dynamic binary is run on my machine, mcore doesn't even reach main, but errors a message to stderr.

**Comment by mossberg** [comment]
But it appears I still have an issue executing dynamic arm binaries that use my system ld.so, and not one i compiled for debugging :/. going to rename this issue to make it more specific

**Comment by mossberg** [comment]
Bounty

**Comment by catenacyber** [comment]
@mossberg do you have binaries to test ? was this fixed by #514 ?

**Comment by mossberg** [comment]
thanks for checking in on this!

the below binary is a hello world arm dynamic binary compiled from

```
#include <stdio.h>
int main(int argc, const char *argv[])
{
    puts("Hello, world!");
    return 0;
}
```
```
arm-linux-gnueabi-gcc helloworld.c  -o hw.arm.dyn2
```

i am now able to get it to successfully run in manticore 0.1.9 using this cmd
```
[N] (tempenv-3eb6291213cd3) mark ubuntu /m/h/c/m/e/linux (master) ❯ manticore hw.arm.dyn2 --env LD_LIBRARY_PATH=/usr/arm-linux-gnueabi/lib
2018-06-07 14:46:32,125: [85553] m.manticore:INFO: Loading program hw.arm.dyn2
2018-06-07 14:47:33,049: [85553] m.manticore:INFO: Generated testcase No. 0 - Program finished with exit status: 0
2018-06-07 14:47:33,056: [85553] m.manticore:INFO: Results in /mnt/hgfs/code/manticore/examples/linux/mcore_nbjIDh
2018-06-07 14:47:33,056: [85553] m.manticore:INFO: Total time: 60.1371490955
[I] (tempenv-3eb6291213cd3) mark ubuntu /m/h/c/m/e/linux (master) ❯ cat mcore_nbjIDh/*.stdout
Hello, world!
```

on my system (ubuntu 16.04) that env variable is necessary for the arm ld.so to find the arm libc

it's not fast, but at least it works, i think we can close this issue now!

[hw.arm.dyn2.zip](https://github.com/trailofbits/manticore/files/2081695/hw.arm.dyn2.zip)

**Comment by catenacyber** [comment]
@mossberg did you have to use a new capstone after https://github.com/aquynh/capstone/pull/1163 ?

**Comment by mossberg** [comment]
No, I was using capstone 3.0.5rc2...so I'm not totally sure what changed so this is fixed now.

**Comment by catenacyber** [comment]
Ok your ld.so must not use arm instruction `ldrd` with addressing mode 3 :-)

**Comment by mossberg** [comment]
what happens for you when you run the commands above on 0.1.9?

**Comment by catenacyber** [comment]
Can you supply me the contents of your `/usr/arm-linux-gnueabi/lib`directory ?

**Comment by mossberg** [comment]
[lib.zip](https://github.com/trailofbits/manticore/files/2081840/lib.zip)

**Comment by catenacyber** [comment]
So, it works for me the same, I get to hello world :-)
