### ISSUE TITLE
Default gas values

### ISSUE THREAD

**Issue by disconnect3d** [trailofbits/manticore#1333]
We haven't thought about that a lot, but we need to set some default gas amounts for different operations:
* creating contract - changed to 3000000 based on remix in https://github.com/trailofbits/manticore/pull/1332
* calling a contract function - currently it is way too high: 0xffffffffffff 
 - https://github.com/trailofbits/manticore/blob/0e90ca3ed6faae89d8f4c549ffd088f57469d549/manticore/ethereum/account.py#L107
* other operations - do we need to set a default value? there are a lot of places in our codebase where we set some arbitrary value:
  - `evm.EVM` constructor: https://github.com/trailofbits/manticore/blob/0e90ca3ed6faae89d8f4c549ffd088f57469d549/manticore/platforms/evm.py#L502
  - `evm.EVM._open_transaction` method: https://github.com/trailofbits/manticore/blob/0e90ca3ed6faae89d8f4c549ffd088f57469d549/manticore/platforms/evm.py#L1981
  - `evm.EVM.create_contract` method: 2300
  - `evm.EVM.transaction` method: 2300
  - `evm.EVM.start_transaction` method: 2300
  - `ManticoreEVM.transaction` method: https://github.com/trailofbits/manticore/blob/0e90ca3ed6faae89d8f4c549ffd088f57469d549/manticore/ethereum/manticore.py#L722
- `Manticore.EVM.multi_tx_analysis` method sets it to 2100000: https://github.com/trailofbits/manticore/blob/0e90ca3ed6faae89d8f4c549ffd088f57469d549/manticore/ethereum/manticore.py#L1016

**Need to be defined:**
- default gas for contract creation
- shall there be different default gas for `solidity_create_contract` and `create_contract`? I think no.
- default gas for `multi_tx_analysis` (CLI)
- do we need default gas for "internal" methods?

@feliam What do you think about ^?

**Comment by feliam** [comment]
Looks like a task for a config value, EVM.DEFAULTGAS for human tx in general. 
If human did not specify what's the max gas she wants in a tx then lets just use a config value for it. Then set the default value to that config value accordingly.

This would fix/apply to solidity_create_contract and create_contract and the tx sent from multi_tx_analysis.

Internal tx have their own way of handling this. gas for internal tx is always explicit and done via EVM code.

**Comment by disconnect3d** [comment]
Okay, let's add a config value `evm.defaultgas`, but:

> If human did not specify what's the max gas she wants in a tx then lets just use a config value for it. 
Where should the user specify it? Shall it be `cfg = config.get_group('evm'); cfg.defaultgas = 123` in theur code OR a `gas=...` argument to given functions?

> Internal tx have their own way of handling this. gas for internal tx is always explicit and done via EVM code.
What do you mean? Is it that the internal txs don't have their own limit and they use the gas from the human tx?

**Comment by feliam** [comment]
I think you need to add/use the default here, and strip it from everywhere else. https://github.com/trailofbits/manticore/blob/0e90ca3ed6faae89d8f4c549ffd088f57469d549/manticore/ethereum/manticore.py#L833

Internal tx do not matter here.

**Comment by disconnect3d** [comment]
The decisions has been made and the changes were added in https://github.com/trailofbits/manticore/pull/1346, so I am closing this issue!
