### ISSUE TITLE
Solidity file must contain exactly one contract or you must use a contract parameter to specify one

### ISSUE THREAD

**Issue by YannickXiong** [trailofbits/manticore#1379]
### OS / Environment
macOS mojave 10.14.1

### Manticore version
Version: 0.2.4

### Python version
python 3.6

### Summary of the problem
manticore ./xxx.sol run failed.
**error 1:** Solidity file must contain exactly one contract or you must use a contract parameter to specify one.
**error 2:** [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/ethereum/parsetab.py'

### Any relevant logs

manticore ./xxx.sol
WARNING: Couldn't create 'manticore.ethereum.parsetab'. [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/ethereum/parsetab.py'
2019-03-05 21:13:18,054: [95966] m.c.manticore:INFO: Verbosity set to 1.
2019-03-05 21:13:18,112: [95966] m.main:INFO: Registered plugins: DetectInvalid, DetectIntegerOverflow, DetectSuicidal, DetectDelegatecall, DetectReentrancySimple, DetectExternalCallAndLeak, DetectUninitializedMemory, DetectEnvInstruction, DetectUninitializedStorage, DetectReentrancyAdvanced, DetectUnusedRetVal
2019-03-05 21:13:18,113: [95966] m.main:INFO: Beginning analysis
2019-03-05 21:13:18,114: [95966] m.e.manticore:INFO: Starting symbolic create contract
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/manticore", line 11, in <module>
    load_entry_point('manticore==0.2.4', 'console_scripts', 'manticore')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/__main__.py", line 41, in main
    ethereum_main(args, logger)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/ethereum/cli.py", line 68, in ethereum_main
    tx_account=args.txaccount, tx_preconstrain=args.txpreconstrain)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 978, in multi_tx_analysis
    args=args, working_dir=working_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 608, in solidity_create_contract
    working_dir=working_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 311, in _compile
    raise EthereumError('Solidity file must contain exactly one contract or you must use a contract parameter to specify one.')
manticore.exceptions.EthereumError: Solidity file must contain exactly one contract or you must use a contract parameter to specify one.

**Comment by disconnect3d** [comment]
Hey,

> error 1: Solidity file must contain exactly one contract or you must use a contract parameter to specify one.
You didn't attach the `xxx.sol` file, so we don't know what is inside - if there are many contracts, just use the `--contract <contract>` parameter. If there aren't, please attach the file.

> error 2: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/ethereum/parsetab.py'
Heh, it's interesting that it came up so late. This file is auto-generated once on the first execution and never changes later on. We should generate it on our side before releasing and add it to the manticore package. Will fix that in the next release.

For now, as a workaround,  please create this file with this content:
```python
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDRESS BOOL BYTES BYTESM COMMA FIXED FIXEDMN FUNCTION INT INTN LBRAKET LPAREN NUMBER RBRAKET RPAREN STRING UFIXED UFIXEDMN UINT UINTN\n     T : UINTN\n     T : UINT\n     T : INTN\n     T : INT\n     T : ADDRESS\n     T : BOOL\n     T : FIXEDMN\n     T : UFIXEDMN\n     T : FIXED\n     T : UFIXED\n     T : BYTESM\n     T : FUNCTION\n     T : BYTES\n     T : STRING\n\n    \n     TL : T\n    \n     TL : T COMMA TL\n    \n     T : LPAREN TL RPAREN\n    \n     T : LPAREN RPAREN\n    \n     T : T LBRAKET RBRAKET\n    \n     T : T LBRAKET NUMBER RBRAKET\n    '

_lr_action_items = {'UINTN':([0,16,24,],[2,2,2,]),'UINT':([0,16,24,],[3,3,3,]),'INTN':([0,16,24,],[4,4,4,]),'INT':([0,16,24,],[5,5,5,]),'ADDRESS':([0,16,24,],[6,6,6,]),'BOOL':([0,16,24,],[7,7,7,]),'FIXEDMN':([0,16,24,],[8,8,8,]),'UFIXEDMN':([0,16,24,],[9,9,9,]),'FIXED':([0,16,24,],[10,10,10,]),'UFIXED':([0,16,24,],[11,11,11,]),'BYTESM':([0,16,24,],[12,12,12,]),'FUNCTION':([0,16,24,],[13,13,13,]),'BYTES':([0,16,24,],[14,14,14,]),'STRING':([0,16,24,],[15,15,15,]),'LPAREN':([0,16,24,],[16,16,16,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,19,21,23,25,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-18,-19,-17,-20,]),'LBRAKET':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,19,20,21,23,25,],[17,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-18,17,-19,-17,-20,]),'COMMA':([2,3,4,5,6,7,8,9,10,11,12,13,14,15,19,20,21,23,25,],[-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-18,24,-19,-17,-20,]),'RPAREN':([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,23,25,26,],[-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,19,23,-18,-15,-19,-17,-20,-16,]),'RBRAKET':([17,22,],[21,25,]),'NUMBER':([17,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'T':([0,16,24,],[1,20,20,]),'TL':([16,24,],[18,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> T","S'",1,None,None,None),
  ('T -> UINTN','T',1,'p_basic_type','abitypes.py',154),
  ('T -> UINT','T',1,'p_basic_type','abitypes.py',155),
  ('T -> INTN','T',1,'p_basic_type','abitypes.py',156),
  ('T -> INT','T',1,'p_basic_type','abitypes.py',157),
  ('T -> ADDRESS','T',1,'p_basic_type','abitypes.py',158),
  ('T -> BOOL','T',1,'p_basic_type','abitypes.py',159),
  ('T -> FIXEDMN','T',1,'p_basic_type','abitypes.py',160),
  ('T -> UFIXEDMN','T',1,'p_basic_type','abitypes.py',161),
  ('T -> FIXED','T',1,'p_basic_type','abitypes.py',162),
  ('T -> UFIXED','T',1,'p_basic_type','abitypes.py',163),
  ('T -> BYTESM','T',1,'p_basic_type','abitypes.py',164),
  ('T -> FUNCTION','T',1,'p_basic_type','abitypes.py',165),
  ('T -> BYTES','T',1,'p_basic_type','abitypes.py',166),
  ('T -> STRING','T',1,'p_basic_type','abitypes.py',167),
  ('TL -> T','TL',1,'p_type_list_one','abitypes.py',175),
  ('TL -> T COMMA TL','TL',3,'p_type_list','abitypes.py',182),
  ('T -> LPAREN TL RPAREN','T',3,'p_tuple','abitypes.py',189),
  ('T -> LPAREN RPAREN','T',2,'p_tuple_empty','abitypes.py',196),
  ('T -> T LBRAKET RBRAKET','T',3,'p_dynamic_type','abitypes.py',203),
  ('T -> T LBRAKET NUMBER RBRAKET','T',4,'p_dynamic_fixed_type','abitypes.py',212),
]
```

**Comment by YannickXiong** [comment]
@disconnect3d  Thanks for your reply.

>  error 2: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/manticore/ethereum/parsetab.py'

The error 2 is resolved, while for the **error 1**, I used `manticore -contract myContractName ./myContract.sol`, it leads to another error. Pls see [1382](https://github.com/trailofbits/manticore/issues/1382)
