### ISSUE TITLE
Implement MOVHPS on x86

### ISSUE THREAD

**Issue by ehennenfent** [trailofbits/manticore#1432]
We've had a couple of issues submitted (#1425, #1411) where the included log file has a line like `m.n.c.abstractcpu:WARNING: Unimplemented instruction: [addr]:	[bytes]	movhps [args]`. Since we've encountered it in the wild, we should add support for the [MOVHPS](https://www.felixcloutier.com/x86/movhps) instruction to Manticore. 

We're prepared to offer a bounty for this issue.

**Comment by agroce** [comment]
@woodruffw thanks!  as soon as we get DeepState working with the Manticore API changes I'll check to make sure, but I suspect it does indeed.
