### ISSUE TITLE
Update Unicorn for better XMM instruction support

### ISSUE THREAD

**Issue by ekilmer** [trailofbits/manticore#1434]
### OS / Environment
Official `trailofbits/manticore` docker image

### Manticore version
Version: 0.2.5

### Python version
Python 3.6.7

### Dependencies
asn1crypto==0.24.0
capstone==4.0.1
cryptography==2.1.4
cytoolz==0.9.0.1
eth-hash==0.2.0
eth-typing==2.1.0
eth-utils==1.5.2
future==0.17.1
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
manticore==0.2.5
ply==3.11
prettytable==0.7.2
pycrypto==2.6.1
pyelftools==0.25
pyevmasm==0.2.0
pygobject==3.26.1
pysha3==1.0.2
pyxdg==0.25
PyYAML==5.1
rlp==1.1.0
SecretStorage==2.3.1
six==1.11.0
toolz==0.9.0
unicorn==1.0.1
z3-solver==4.8.5.0

### Summary of the problem
The current installation of Unicorn is too old to properly decode the following instruction
```
c5 f1 64 fc     vpcmpgtb        xmm7, xmm1, xmm4
```
and it kills Manticore during a run with
```
2019-05-15 19:58:53,586: [437] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffb5065f:        c5 f1 64 fc     vpcmpgtb        xmm7, xmm1, xmm4
2019-05-15 19:58:53,588: [437] m.n.c.abstractcpu:ERROR: Unimplemented instruction: 0x00007fffffb5065f:  c5 f1 64 fc     vpcmpgtb        xmm7, xmm1, xmm4
2019-05-15 19:58:53,590: [437] m.c.executor:ERROR: Exception: Invalid instruction (UC_ERR_INSN_INVALID)
```

### Step to reproduce the behavior
The version of unicorn installed can be invoked by running the following script with `python3 unicorn_fail.py` within the `trailofbits/manticore` docker image.
```
#!/usr/bin/env python
# Sample code for X86 of Unicorn. Nguyen Anh Quynh <aquynh@gmail.com>

from __future__ import print_function
from unicorn import *
from unicorn.x86_const import *

# This is the instruction that isn't supported with old Unicorn installed in Docker
X86_CODE64_XMM = b"\xc5\xf1\x64\xfc" # vpcmpgtb xmm7, xmm1, xmm4

# memory address where emulation starts
ADDRESS = 0x1000000

# callback for tracing basic blocks
def hook_block(uc, address, size, user_data):
    print(">>> Tracing basic block at 0x%x, block size = 0x%x" %(address, size))

def hook_code64(uc, address, size, user_data):
    print(">>> Tracing instruction at 0x%x, instruction size = 0x%x" %(address, size))
    rip = uc.reg_read(UC_X86_REG_RIP)
    print(">>> RIP is 0x%x" %rip);

def test_x86_64_XMM():
    print("Emulate x86_64 code")
    try:
        # Initialize emulator in X86-64bit mode
        mu = Uc(UC_ARCH_X86, UC_MODE_64)

        # map 2MB memory for this emulation
        mu.mem_map(ADDRESS, 2 * 1024 * 1024)

        # write machine code to be emulated to memory
        mu.mem_write(ADDRESS, X86_CODE64_XMM)

        # initialize machine registers
        mu.reg_write(UC_X86_REG_XMM1, 0x000102030405060708090a0b0c0d0e0f)
        mu.reg_write(UC_X86_REG_XMM4, 0x00102030405060708090a0b0c0d0e0f0)
        mu.reg_write(UC_X86_REG_XMM7, 0x00102030405060708090a0b0c0d0ffff)

        # tracing all basic blocks with customized callback
        mu.hook_add(UC_HOOK_BLOCK, hook_block)

        # tracing all instructions with customized callback
        mu.hook_add(UC_HOOK_CODE, hook_code64)

        try:
            # emulate machine code in infinite time
            mu.emu_start(ADDRESS, ADDRESS + len(X86_CODE64_XMM))
        except UcError as e:
            print("ERROR: %s" % e)

        # now print out some registers
        print(">>> Emulation done. Below is the CPU context")

        r_xmm1 = mu.reg_read(UC_X86_REG_XMM1)
        r_xmm4 = mu.reg_read(UC_X86_REG_XMM4)
        r_xmm7 = mu.reg_read(UC_X86_REG_XMM7)
        print(">>> XMM0 = 0x%.64x" %r_xmm1)
        print(">>> XMM0 = 0x%.64x" %r_xmm4)

    except UcError as e:
        print("ERROR: %s" % e)

if __name__ == '__main__':
    print("=" * 35)
    test_x86_64_XMM()
```

### Expected behavior
With the latest version of Unicorn (from `master`) I don't get the `UC_ERR_INSN_INVALID` error.
```
Emulate x86_64 code
>>> Tracing basic block at 0x1000000, block size = 0x4
>>> Tracing instruction at 0x1000000, instruction size = 0x4
>>> RIP is 0x1000000
>>> Emulation done. Below is the CPU context
>>> XMM0 = 0x00000000000000000000000000000000000102030405060708090a0b0c0d0e0f
>>> XMM0 = 0x0000000000000000000000000000000000102030405060708090a0b0c0d0e0f0
```

### Actual behavior
With the version of Unicorn installed in the Docker image I get the error.
```
Emulate x86_64 code
>>> Tracing basic block at 0x1000000, block size = 0x3
>>> Tracing instruction at 0x1000000, instruction size = 0xf1f1f1f1
>>> RIP is 0x1000000
ERROR: Invalid instruction (UC_ERR_INSN_INVALID)
>>> Emulation done. Below is the CPU context
>>> XMM0 = 0x00000000000000000000000000000000000102030405060708090a0b0c0d0e0f
>>> XMM0 = 0x0000000000000000000000000000000000102030405060708090a0b0c0d0e0f0
```

### Any relevant logs
Output of unicorn script with error is posted above.

I tried to update and install Unicorn from `master` and run Manticore, but I get segfault on the first unimplemented instruction:
```
2019-05-15 21:00:55,666: [690] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdc1864:        0f 16 85 68 ff ff ff    movhps  xmm0, qword ptr [rbp - 0x98]
./manticore_process.sh: line 30:   690 Segmentation fault  
```

I'm also not sure where Unicorn added support for this instruction.

**Comment by ehennenfent** [comment]
Unfortunately, Unicorn's `master` is [200+ commits ahead](https://github.com/unicorn-engine/unicorn//compare/1.0.1...HEAD) of version 1.01. Since the dockerfile uses `pip install` to retrieve our dependencies, the easiest way to fix this is to wait for the Unicorn team to push a new version to PyPi. Unfortunately, unicorn-engine/unicorn#1066 looks rather dead. 

As a workaround, you could create a new dockerfile based on the manticore image already on Dockerhub. Something like this:
(Apologies as I haven't written a dockerfile in a long while)
```
FROM trailofbits/manticore
RUN pip3 uninstall unicorn]
RUN git clone https://github.com/unicorn-engine/unicorn.git
< follow the Unicorn build commands in [compile.md](https://github.com/unicorn-engine/unicorn/blob/master/docs/COMPILE-NIX.md) >

CMD /bin/bash

```

**Comment by ekilmer** [comment]
I did try building Unicorn from master, but I seem to be getting weird results with no progress being made on the first instance of an unsupported instruction that requires the fallback emulator. In my case it was
```
0f 16 85 68 ff ff ff    movhps  xmm0, qword ptr [rbp - 0x98]
```

This behavior is likely due to assumptions/workarounds made about the 1.01 version of Unicorn in TODO comments within Manticore about [broken register naming](https://github.com/trailofbits/manticore/blob/a527e818301e36e7f7005db4d2f5999b38d6453a/manticore/utils/fallback_emulator.py#L152-L154), [system register read/write](https://github.com/trailofbits/manticore/blob/a527e818301e36e7f7005db4d2f5999b38d6453a/manticore/utils/fallback_emulator.py#L176-L182), and [XMM and YMM register mappings](https://github.com/trailofbits/manticore/blob/a527e818301e36e7f7005db4d2f5999b38d6453a/manticore/utils/fallback_emulator.py#L225-L230), to name just a few.

This is the Dockerfile I used:
```
FROM trailofbits/manticore

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get -y install python cmake

# Unicorn
WORKDIR deps
RUN pip3 uninstall -y unicorn
RUN git clone https://github.com/unicorn-engine/unicorn.git
WORKDIR unicorn
RUN UNICORN_QEMU_FLAGS="--python=/usr/bin/python" ./make.sh && ./make.sh install
WORKDIR bindings/python
RUN python3 setup.py install

WORKDIR /manticore
RUN pip3 install --no-binary keystone-engine -e .[dev]
```

**Comment by ekilmer** [comment]
Re-opening this since PR #1459 reverts #1440 . Will wait for a release of Unicorn to be pushed to PyPi before resolving this issue.

In the mean-time, a patch similar to what was changed in #1440 should be a work-around.

**Comment by disconnect3d** [comment]
@ekilmer See https://pypi.org/project/unicorn/1.0.2rc1/#history
