### ISSUE TITLE
AttributeError: 'Manticore' object has no attribute 'terminate'

### ISSUE THREAD

**Issue by 0x6b7966** [trailofbits/manticore#1499]
### OS / Environment

Description:	Ubuntu 16.04.5 LTS

### Manticore version

Version: 0.3.0
### Python version

Python 3.6.8

### Summary of the problem
AttributeError: 'Manticore' object has no attribute 'terminate'

### Step to reproduce the behavior
from manticore.native import Manticore

m = Manticore('./multiple-styles')

m.terminate()

**Comment by ehennenfent** [comment]
You probably want `m.kill()` or possibly `m.finalize()`. Did you see `m.terminate()` in an example somewhere? If so, where?

**Comment by 0x6b7966** [comment]
Thank you !
I see it in the following file 
trailofbits/manticore/blob/master/examples/linux/binaries/symbolic_solve.py   line 34 .
