### ISSUE TITLE
Adding the ability to specify solidity version

### ISSUE THREAD

**Issue by Mikerah** [trailofbits/manticore#1550]
I'm currently working on a project that analyzes a few thousand smart contracts written in various version of solidity. Although manticore gives one the ability to specify a range of supported solidity versions through the `pragma` modifier, if a given contract uses old modifiers e.g. `constant` instead of `pure` or `view`, it will not run, as current versions of solidity no longer consider this a warning but instead an error. I cannot go into each file and make the specified changes as this would mess with the result results.

Is there a way to somehow specify this? If not, what is needed to add this to the codebase? I, personally, wouldn't mind taking the time to add this feature myself.

**Comment by feliam** [comment]
That sounds great! Lets see..
Manticore only really supports and pass upstream tests for Frontier.  Manticore does not really depends in solidity (you can analyze contracts that came from vyper or from the bytecode) 
Apparently there is a way to specify target fork of the compilation via  --evm-version.

```
  --evm-version version
                       Select desired EVM version. Either homestead, 
                       tangerineWhistle, spuriousDragon, byzantium, 
                       constantinople, petersburg (default), istanbul or 
                       berlin.
```

So if that command line modifier works there should be a way to configure crytic-compile to always target our supported fork. (https://github.com/crytic/crytic-compile/wiki/Configuration) Mcore uses that project to transform solidity and others into bytecode. CTRL+F crytic

---
If we can not control the target evm assemble of a compilation then to support newer solidity, manticore would first need to have a way to support newer evm instructions correctly. Either ignoring older forks or having a way to run different EVM versions depending on the block number or configuration.

**Comment by montyly** [comment]
Hi @Mikerah ,

You can use the `--solc-solcs-bin` flag to specify different `solc` binary versions to try. If you have [`solc-select`](https://github.com/crytic/solc-select/) installed you can use the `--solc-solcs-select` flag.

For example:
```solidity
pragma solidity 0.4.24; // Fail with a solc version != 0.4.24

contract C{
}
```
```
$ manticore test.sol --solc-solcs-bin solc-0.5.11,solc-0.4.24 # solc-0.5.11 and solc-0.4.24 are two different binaries in $PATH
```
or
```
$ manticore test.sol --solc-solcs-select 0.5.11,0.4.24 # solc-select is installed
```

Will first try to compile the code with 0.5.11, and then use 0.4.24.

**Comment by Mikerah** [comment]
What is the equivalent of passing this flag to the `ManticoreEVM` class if there's any?
