### ISSUE TITLE
Transparently compress Manticore persisted state files

### ISSUE THREAD

**Issue by bradlarsen** [trailofbits/manticore#1622]
In recent versions of Manticore, it looks like each state is persisted to disk as a Python pickle file.  When using Manticore on a more complicated binary, where at least thousands of states are explored, these persisted states take up lots of space!  (A VM I was using had its 60GB disk fill up entirely when analyzing a realistic program.)

I noticed that if these states are compressed with gzip, they shrink by 10x or more.

It would be friendlier if Manticore would transparently compress & decompress its persisted states using gzip.  This might possibly not even slow Manticore down at all, depending on how expensive I/O operations are.

**Comment by reaperhulk** [comment]
You should be able to replace any `open` calls with calls to `gzip.open` and then the interface for writing (`filehandle.write()`) remains unchanged.
