### ISSUE TITLE
How many smart contract bugs can manticore detect?

### ISSUE THREAD

**Issue by xf97** [trailofbits/manticore#1663]
We are conducting a study to evaluate smart contract analysis tools, so we want to understand the kinds of smart contract bugs that manticore can detect. We read manticore's papers and blogs and didn't find an answer that can answer our questions, so we ask you questions.

**Comment by feliam** [comment]
ManticoreEVM attempts to explore all possible code paths of your contract and generate concrete input to let you reproduce each path. It generates interesting deep testcases out of thin air using solely the bytecode.

Some of these paths/testcases may potentially break the invariant you want to maintain in your contract. This depends deeply in the nature of your contract and invariant.

That said.
We have added a number of canned detectors that try to mark some of the paths where the contract is "obviously" doing something the programmer did not want.

Please join us in here for more q&a? https://empireslacking.herokuapp.com/

**Comment by montyly** [comment]
For info @xf97, we use Manticore as a targeted tool, to verify custom properties. You will find examples of properties in our [audit reports](https://github.com/trailofbits/publications/#ethereum-smart-contracts), for example here: https://github.com/trailofbits/publications/blob/master/reviews/BalancerCore.pdf. 

To detect generic bugs we use [Slither](https://github.com/crytic/slither). It has 45 public detectors. If you use [crytic.io](https://crytic.io/), you will get access to ~40 additional detectors.
