### ISSUE TITLE
Add properties verifier mode

### ISSUE THREAD

**Issue by montyly** [trailofbits/manticore#1664]
We should add a cli-option, were given a contract, a prefix and a number of transactions:
```
manticore-verifier . --contract MyContract --txs 2 --prefix crytic_
```
Manticore would:
- Deploy the contract `MyContract`
- Call the contract with `2` symbolic transaction (with a filter on constant functions)
- Between each symbolic transaction, every functions that start with `crytic_` will be checked

The goal is to have a common framework for which we can check properties with Echidna and Manticore without extra effort. This should also be compatible with the upcoming [`slither-prop`](https://github.com/crytic/slither/pull/428) tool.

For the long run, we can integrate other stuff like:
- If the function is `prefix_` + `revert` , then the property should revert and not fail
- We could integrate some info from the Slither's echidna printer (ex: what are the list of function that impact the other functions, to filter the symbolic transactions, the functions with assert to be checked)

**Comment by MatthewARinehart** [comment]
`Manticore verifier merged to master` from prioritization exercise
