### ISSUE TITLE
MemoryException from running `basic`

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#181]
Probably an emulation bug

[basic.slam.zip](https://github.com/trailofbits/manticore/files/953898/basic.slam.zip)

### OS / Environment
Ubuntu 16.10

**Comment by skxo** [comment]
Exactly the same error
[11605][0] EXECUTOR:ERROR: MemoryException at PC: 0x000000000041c79b. Cause: No access reading
2017-04-25 18:18:05,856: [11605][0] EXECUTOR:INFO: Generating testcase No. 1 for state No.0 - Memory Exception: No access reading <00000008>

OS / Environment

Linux-VirtualBox 4.8.0-49-generic #52-Ubuntu SMP Thu Apr 20 09:38:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

please advice will be really nice.

**Comment by mossberg** [comment]
thanks for the bug report @skxo! the binary that got compiled on your system likely is triggering an emulator error we haven't seen before in manticore that is causing the program to incorrectly segfault (it tried to dereference 0x8, which is why it printed Memory Exception). in the meantime if you want to try manticore, look here: https://gist.github.com/ehennenfent/a5ad9746615d1490c618a88b98769c10 . the first link in the writeup is the link to the binary itself, and those manticore scripts in the writeup should work.
