### ISSUE TITLE
Memory exception for all examples on ARM due to TLS issue

### ISSUE THREAD

**Issue by lgeek** [trailofbits/manticore#182]
### OS / Environment
Arch Linux ARM (AArch32)

### Python version
Python 2.7.13

### Dependencies
alabaster==0.7.10
appdirs==1.4.3
Babel==2.4.0
capstone==3.0.4
coverage==4.3.4
docutils==0.13.1
imagesize==0.7.1
Jinja2==2.9.6
keystone-engine==0.9.1.post3
-e git+https://github.com/trailofbits/manticore.git@44dff1745d2c5952fb947d13e26b0177bdd6221a#egg=Manticore
MarkupSafe==1.0
nose==1.3.7
packaging==16.8
ply==3.10
pyelftools==0.24
Pygments==2.2.0
pyparsing==2.2.0
pytz==2017.2
requests==2.13.0
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.5.5
unicorn==1.0.0

### Summary of the problem
A memory exception is thrown for all example executables I've built on ARM

### Actual behavior
```
Command line:
  /usr/bin/manticore ./helloworld
Status:
  Memory Exception: No access writing <0000001c>

================ PROC: 00 ================
Memory:
  0000000000010000-0000000000086000  r x 00000000 ./helloworld
  0000000000095000-0000000000097000  rw  00075000 ./helloworld
  0000000000097000-0000000000098000  rw  00000000 
  00000000bffdf000-00000000c0000000  rwx 00000000 
  00000000f7fff000-00000000f8000000  rw  00000000 
  00000000ffff0000-00000000ffff1000  r x 00000000 
CPU:
INSTRUCTION: 0x00000000000234ac:	str	r6, [r2, r3]
 R0: 0x000000000000000a
 R1: 0x0000000000000000
 R2: 0x0000000000000000
 R3: 0x000000000000001c
 R4: 0x0000000000000009
 R5: 0x00000000bfffff52
 R6: 0x00000000000955f8
 R7: 0x0000000000000055
 R8: 0x0000000000000000
 R9: 0x0000000000000000
R10: 0x0000000000000000
R11: 0x0000000000000000
R12: 0x0000000000096b18
R13: 0x00000000bfffed46
R14: 0x0000000000023860
R15: 0x00000000000234b0
APSR: 0x00000000a0000000
  Instruction: 0x234ac	(str r6, [r2, r3])
```

We can see the issue is that r2 has the value 0. DIssasembling the function in which this occurs, we can determine that the value in R2 was copied from the TLS register:

```
Dump of assembler code for function ptmalloc_init.part.6:
[....]
   0x000234a0 <+36>:    mrc     15, 0, r2, cr13, cr0, {3}
   0x000234a4 <+40>:    ldr     r3, [pc, r3]
   0x000234a8 <+44>:    cmp     r5, r1
   0x000234ac <+48>:    str     r6, [r2, r3]
```

The executable is attached [here](https://github.com/trailofbits/manticore/files/953973/hw.zip).

**Comment by lgeek** [comment]
The TLS value is set via the `__ARM_NR_set_tls` syscall, called from the __libc_setup_tls (0x00010954) function in this executable.

**Comment by GarretReece** [comment]
Ongoing work against this binary--the initial issue has been fixed, but that's exposed a number of thumb specific semantics and instructions that need/needed implementation. Thus far: `bx`, `blx`, `mrc`, `movc`, `utxb`, `ldrex`, `strex`, `ldrd`, `strd`, and `lsl.w` have all been implemented or updated. 

Still to go: `orn`, `itt ne`, and `uadd8`.  More to come after those, I suspect.

**Comment by GarretReece** [comment]
`orn`, `it`, `uadd8`, `sel`, `sxth`, `rev`, and `cbnz` all implemented. `add <dest>, <op>` flavor of add now supported. The binary seems to run to completion now.

**Comment by mossberg** [comment]
pending merge of #403
