### ISSUE TITLE
Formalize API for adding constraints to State

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#195]
Currently, we informally have a `State.add` API that is used internally for adding constraints onto a State. It can incidentally be used as a public API, but this was never decided deliberately, so I think we should take some time to actually think if there's anything that should be improved.

imo, it's good except, should be renamed to `State.constrain`.

**Comment by mossberg** [comment]
that said, z3's analogous api is called `Solver.add`, so maybe if we want to be familiar, we should keep it how it is. i still do think `constrain` is more descriptive.
http://z3prover.github.io/api/html/z3.html

**Comment by frapik99** [comment]
@mossberg , I think it would be nice to follow this approach:
```add_constraint``` for adding a new constraint, ```constraint(id)``` for retrieving an already added constraint (is it useful??), ```constraints``` for retrieving all of them and ```remove_constraint(id)``` for removing a constraint (maybe not necessary)

Thanks

**Comment by mossberg** [comment]
Cool ideas! I'm not exactly sure of uses cases for retrieving individual constraints or removing them, so in the name of minimalism, I'd prefer to just keep it to an API for adding constraints. As far as naming, we discussed internally and like the terseness of simply `.constrain`, and will likely go with this.

**Comment by frapik99** [comment]
thanks @mossberg I understand opinion and I'll accept it.

Thanks
