### ISSUE TITLE
Windows minidumps require args defined in script usage

### ISSUE THREAD

**Issue by securedorg** [trailofbits/manticore#206]
### OS / Environment

Ubuntu 16.04

### Python version

2.7

### Summary of the problem
https://github.com/trailofbits/manticore/blob/master/manticore/manticore.py#L73
makeWindows is expected args to be populated. Args is typically set in main's parsed arguments but not available in scripts.

### Step to reproduce the behavior
python run_simple.py backup_00340000.dmp

### Expected behavior
N/A

### Actual behavior
```
Traceback (most recent call last):
  File "run_simple.py", line 17, in <module>
    m.run()
  File "/usr/local/lib/python2.7/dist-packages/manticore/manticore.py", line 537, in run
    state = self._make_state(self._binary)
  File "/usr/local/lib/python2.7/dist-packages/manticore/manticore.py", line 344, in _make_state
    state = makeWindows(self._args)
  File "/usr/local/lib/python2.7/dist-packages/manticore/manticore.py", line 73, in makeWindows
    assert args.size is not None, "Need to specify buffer size"
AttributeError: 'list' object has no attribute 'size'
```

**Comment by DigiAngel** [comment]
I see this exact issue, even after specifying --buffer.

**Comment by mossberg** [comment]
As this issue shows, our windows support is unfortunately super neglected and bitrotted due to current priorities, and has been for some time 😞  we're planning on redoing it, i am going to close this for now, but thanks a lot!
