### ISSUE TITLE
CPUID reports AVX2 support, but unicorn doesn't support `vinserti128`

### ISSUE THREAD

**Issue by simon-bourne** [trailofbits/manticore#210]
I'm putting together a pull request to fix this presently.

### OS / Environment

No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

### Python version
Python 2.7.12

### Dependencies

alabaster==0.7.7
attrs==15.2.0
Babel==1.3
BeautifulSoup==3.2.1
blinker==1.3
capstone==3.0.4
chardet==2.3.0
cldoc==1.9
configglue==1.1.2
configobj==5.0.6
coverage==4.3.4
cryptography==1.2.3
debtags==2.0
defer==1.0.6
dirspec==13.10
docutils==0.12
duplicity==0.7.6
ecdsa==0.13
enum34==1.1.2
feedparser==5.1.3
gyp==0.1
httplib2==0.9.1
idna==2.0
ipaddress==1.0.16
Jinja2==2.8
keystone-engine==0.9.1.post3
lockfile==0.12.2
lxml==3.5.0
Mako==1.0.3
-e git+git@github.com:simon-bourne/manticore.git@8d6bcadb3752010943fd6645a13e2c3457d69ac9#egg=manticore
MarkupSafe==0.23
nemo-emblems==3.2.3
netifaces==0.10.4
nose==1.3.7
oauthlib==1.0.3
oneconf==0.3.9
PAM==0.4.2
paramiko==1.16.0
pexpect==4.0.1
Pillow==3.1.2
piston-mini-client==0.7.5
ply==3.10
protobuf==2.6.1
ptyprocess==0.5
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0
pyelftools==0.24
Pygments==2.1
pygobject==3.20.0
pygpgme==0.3
pyinotify==0.9.6
PyJWT==1.3.0
pyOpenSSL==0.15.1
pyparsing==1.5.7
pyparted==3.10.7
pyserial==3.0.1
pysmbc==1.0.15.5
Pyste==0.9.10
python-apt==1.1.0b1
python-debian==0.1.27
python-xlib==0.14
pytz==2014.10
pyxdg==0.25
reportlab==3.3.0
requests==2.9.1
roman==2.0.0
service-identity==16.0.0
setproctitle==1.1.8
six==1.10.0
Sphinx==1.3.6
sphinx-rtd-theme==0.1.9
Twisted==16.0.0
unicorn==1.0.0
urllib3==1.13.1
uTidylib==0.2
youtube-dl==2016.2.22
zope.interface==4.1.3

### Summary of the problem

`memset` selects implementation based on CPUID and uses `vinserti128` which is unsupported by unicorn.

### Step to reproduce the behavior

Call `memset` from a C++ static binary built with `clang`.

### Expected behavior

Run through without invalid instruction.

### Actual behavior

`2017-04-28 08:29:41,174: [30945][0] CPU:INFO: Unimplemented instruction: 0x00000000005547c0:	c4 e3 7d 38 c0 01	vinserti128	ymm0, ymm0, xmm0, 1`

**Comment by dguido** [comment]
Fixed in #211, thanks!
