### ISSUE TITLE
X86 syscall arg registers are backwards between amd64 and i386 (linux)

### ISSUE THREAD

**Issue by chronoslynx** [trailofbits/manticore#224]
See https://github.com/trailofbits/manticore/commit/065266ba7f767fcf18da53c6f09b82d484eeeafd#diff-f7a40927c049b8198401146c679d368aL1921 for the commit that changed it. 

If the architecture is `i386` then the `syscall_arg_regs` are the registers for the amd64 syscall ABI and vice-versa

Edit: I'm pulling the code down to swap them & verify that tests pass, etc.

**Comment by mossberg** [comment]
thanks!

**Comment by chronoslynx** [comment]
I seem to get the same test failures on both current master and my branch; the following fail when run via nosetests:
- `testBitvector_max1`
- `testBitvector_max`
- `testBasicSymbolic`

**Comment by mossberg** [comment]
Hm, odd. Thanks for looking into this, feel free to join our slack also if you haven't already https://empireslacking.herokuapp.com/

**Comment by chronoslynx** [comment]
Aha! The function that calls Z3's minimize doesn't eat the output that follows (which is the simplified representation of the requested symbol), pushing the solver interface out of alignment. Testing a fix now

**Comment by chronoslynx** [comment]
I'm pulling that into a separate issue; it fixes the test failure, and is due to a nondeterministic behavior in Z3 (full details in an issue I'm writing).

Do you want me to issue a pull request with this fix?
