### ISSUE TITLE
state.solve_n should not use a default parameter for nsolves

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#230]
the nsolves parameter currently defaults to 1, but that is exactly what solve_one should be used for. i think we should remove the default parameter from state.solve_n

**Comment by feliam** [comment]
Also as suggested by smtlib the common name for solving is get_value. Maybe that's what a user may expect.
Also policy not used in solve_n.
Also exceptions not documented(which may happen when less solutions than requested exists)

https://github.com/trailofbits/manticore/blob/fd3873f0a872c2e37a82adafee86822bb75e9967/manticore/core/state.py#L214-L223
