### ISSUE TITLE
Manticore can't work on EVM due to crytic-compile's latest release

### ISSUE THREAD

**Issue by montyly** [trailofbits/manticore#2451]
This is a known issue, that should be visible to the users.

Crytic-compile had breaking changes with [0.2.0](https://github.com/crytic/crytic-compile/releases/tag/0.2.0)

Until https://github.com/trailofbits/manticore/pull/2444 is merged, and we have a new Manticore's release, the installation through pip or github is broken for EVM.

As a temporary workaround: users can downgrade `crytic-compile`:
```
$ pip install -Iv crytic-compile==0.1.13
```

If you use also Slither, I recommend to do this in a virtual environment, as downgrading `crytic-compile` will break Slither.

**Comment by alexon1234** [comment]
The PR is merged, can we close this issue?

**Comment by montyly** [comment]
Hi @alexon1234, I think we can keep it open until the next release (https://github.com/trailofbits/manticore/pull/2456), for users' awareness

**Comment by ehennenfent** [comment]
Closed w/ #2456
