### ISSUE TITLE
Check if capstone hacks are still necessary

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#263]
As of #262 we use a newer capstone, and our various hacks around it may not be necessary. Most of these are in arm.py iirc, but grepping for capstone should locate them.

**Comment by japesinator** [comment]
I'm not sure this is an exhaustive list, but:

  * Capstone still seemingly computes `update_flags` for `adc` incorrectly

  * RRX shifts are apparently still computed as 0 instead of 1
  *

**Comment by japesinator** [comment]
I'm not sure this is an exhaustive list, but:

  * Capstone still seemingly computes update_flags for adc incorrectly

  * RRX shifts are apparently still computed as 0 instead of 1

  * Capstone still labels some instructions as `mov` incorrectly

  * Writeback looks to still be set incorrectly
