### ISSUE TITLE
Misspelled "ConcretizeArgument"

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#361]
We had a typo in some refactor and ConcretizeArgument is misspelled as ConcretizeArgumet in lots of places.

**Comment by ffio123** [comment]
Can I take this?

**Comment by ffio123** [comment]
[manticore-master.zip](https://github.com/trailofbits/manticore/files/1110949/manticore-master.zip)
EXE was removed as it could not be read. Should just be able to reupload.

**Comment by ffio123** [comment]
Finished. Just need access to push.

**Comment by mossberg** [comment]
hi, thanks for looking at this! could you please submit a pull request?

**Comment by ffio123** [comment]
I'm new to this. When I try to submit the pull request it states "Sync failed to push local changes. It seems you do not have permission to push your changes to this repository."

**Comment by mossberg** [comment]
fixed by #366
