### ISSUE TITLE
State counter / identifier

### ISSUE THREAD

**Issue by montyly** [trailofbits/manticore#373]
The commit 520a9be47d4df0cdb4990c3b4f81318574bde8ed removed the [state](https://github.com/trailofbits/manticore/blob/master/manticore/core/state.py) counter variable (`state.co`, assigned by the function `state.get_new_id()`). This variable is used as an identifier by `state.generate_inputs`, to generate unique filenames per state (see [smtfile](https://github.com/trailofbits/manticore/blob/master/manticore/core/state.py#L323), [input](https://github.com/trailofbits/manticore/blob/master/manticore/core/state.py#L333) and [input file](https://github.com/trailofbits/manticore/blob/master/manticore/core/state.py#L345)).

Is there any other identifier that can be used to differentiate the states?

**Comment by feliam** [comment]
A State may contain a platform that does not have files. So maybe better to do it at manticore.py via events ?
Something like this: https://github.com/trailofbits/manticore/blob/master/manticore/core/executor.py#L344-L371

**Comment by montyly** [comment]
Yes, it makes sense. 
Or maybe we can add a generic `generate_symbolic_inputs()` in [plateform](https://github.com/trailofbits/manticore/blob/master/manticore/platforms/platform.py), and then let each platform handling the possible symbolic inputs (which can be files, network, ..) for the targeted system?

**Comment by mossberg** [comment]
I agree with @montyly, I think we could move the platform specific code here (https://github.com/trailofbits/manticore/blob/master/manticore/core/state.py#L340-L352) to the Platform, and replace that code with something like `self.platform.generate_symbolic_inputs()` (or some other name). That platform function would either actually write to the workspace itself, or return some data which is written to the workspace by `state.generate_inputs`.

**Comment by mossberg** [comment]
@feliam what do you think of the above idea?

**Comment by mossberg** [comment]
#438 is some work at reimplementing `state.generate_inputs` using the new workspace, output and events infrastructure. It does not separate platform specific code from testcase generation code yet. @feliam can you let me know what you think?

**Comment by mossberg** [comment]
@montyly As of current Manticore master, `state.generate_testcase` exists (effectively replaces the old `state.generate_inputs`), so you can use that now!
