### ISSUE TITLE
How to install manticore on CentOS 5 (a very old OS)?

### ISSUE THREAD

**Issue by vencentchow** [trailofbits/manticore#375]
I am struggling with installing manticore on CentOS 5. When l ran the program like this:
`[root@system]# manticore`
I got:
`z3: /usr/lib/libgomp.so.1: version GOMP_4.0 not found (required by z3)`
`z3: /usr/lib/libstdc++.so.6: version CXXABI_1.3.5 not found (required by z3)`
`z3: /usr/lib/libstdc++.so.6: version CXXABI_1.3.8 not found (required by z3)`
`z3: /usr/lib/libstdc++.so.6: version GLIBCXX_3.4.11 not found (required by z3)`
`z3: /usr/lib/libstdc++.so.6: version GLIBCXX_3.4.18 not found (required by z3)`
`z3: /usr/lib/libstdc++.so.6: version GLIBCXX_3.4.9 not found (required by z3)`
`z3: /usr/lib/libstdc++.so.6: version GLIBCXX_3.4.15 not found (required by z3)`
`z3: /usr/lib/libstdc++.so.6: version GLIBCXX_3.4.20 not found (required by z3)`

And I tried to upgrade libgomp.so.1 and libstdc++.so.6, but failed, due to my version of glibc <= 2.10. How could I overcome these problems? Could you please give me a hint?

**Comment by japesinator** [comment]
I'm not sure how best to get the library versions Z3 needs, but have you considered using [Docker](https://github.com/trailofbits/manticore/blob/master/Dockerfile)?

**Comment by vencentchow** [comment]
Thanks a lot for your reply @japesinator. I am not very familiar with [Docker](https://github.com/trailofbits/manticore/blob/master/Dockerfile). My target program is running on the CentOS 5, and no source code is available. How could I extract dependecies of the program into a docker image? Any tips?

**Comment by japesinator** [comment]
We provide a [Dockerfile](https://github.com/trailofbits/manticore/blob/master/Dockerfile) you can use, but if only the program is running on CentOS 5, you can also just extract the binary and perform the analysis on a more modern system.

**Comment by vencentchow** [comment]
Highly appreciate your help @japesinator. This question is entangled with many others. Firstly, my target program is running on a netwrok device, not a stardard PC. So it spends a lot of effort to run it on a modern system. Secondly, the Cent OS 5 on the device is x86, and it is said it is not supported by Docker. Am I annoying? Sorry for that.

**Comment by mossberg** [comment]
@vencentchow perhaps try compiling a statically linked version of z3 on that centos 5 system and putting that in your $PATH?

**Comment by mossberg** [comment]
I'm going to close this for now, please reopen if it's still relevant.
