### ISSUE TITLE
'Manticore' object has no attribute 'dump_stats'

### ISSUE THREAD

**Issue by small-evil-beast** [trailofbits/manticore#412]
I have a problem with the example,manticore has no attribute dump_stats,and there is no result in api search,is this method abandon? And which methd is the replace.

3ks....

**Comment by KnoooW** [comment]
damn good question....

**Comment by japesinator** [comment]
`dump_stats` has been removed from our API, what functionality from it do you need in particular?

**Comment by small-evil-beast** [comment]
get，i just test the examples/script/*,some script use this method,so i have this problem...

**Comment by japesinator** [comment]
We should definitely update those scripts, I'll add an issue to do that

**Comment by mossberg** [comment]
Since we have 424 tracking this issue, I'm going to close this, thanks for the reports!
