### ISSUE TITLE
Document gotchas

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#419]
Manticore has a number of "gotchas": quirks or little things you need to do in a certain way otherwise you'll have crashes and other unexpected results. Known gotchas should be documented so users can be aware of them, and so we can be aware of them and strive to eliminate them.

**Comment by mossberg** [comment]
some initial gotchas

- something like `m.context['flag'].append('a')` inside a hook will not work. you need to do `m.context['flag'] += ['a']`. this is related to multiprocessing syncmanager dictproxy stuffhttps://docs.python.org/2.7/library/multiprocessing.html#multiprocessing.managers.SyncManager.list
- you need to use the `+` character to demark symbolic data (manticore will not automatically symbolicate arguments) (from a question in support chat)

**Comment by feliam** [comment]
Also if you had to handle 2 different items in the context it may get interleaved in the middle. m.context['flag1'] += ['a']
--- interrupted by other worker
m.context['flag2] += ['b']

So you need to use 
with m.locked_context() as global_context:
     global_context['flag1'] += ['a'] 
     global_context['flag2'] += ['b']

**Comment by feliam** [comment]
You also have 
with  m.locked_context('flag') as flag_context:
     flag_context.append('a')
