### ISSUE TITLE
Linux Platform: Support for socket family of syscalls

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#422]
Manticore should be able to analyze server applications, specifically ones that use the following syscalls: socket, bind, listen, accept, send, recv, sendfile

**Comment by yan** [comment]
Basic support added in #428

**Comment by mossberg** [comment]
Awesome! Are there any clear next steps or improvements that make sense?

**Comment by mossberg** [comment]
Now that #428 is merged and "basic" support has been added, @yan what do you think constitutes completion of this issue?

**Comment by yan** [comment]
I think this constitutes basic support; closing for now and will revisit once we need more involved support.
