### ISSUE TITLE
Update example scripts to not use `dump_stats`

### ISSUE THREAD

**Issue by japesinator** [trailofbits/manticore#424]
We don't currently have `dump_stats` in the API, but it's used in a [bunch](https://github.com/trailofbits/manticore/search?utf8=%E2%9C%93&q=dump_stats&type=) of example scripts

**Comment by japesinator** [comment]
Ref. #412

**Comment by mossberg** [comment]
note: the work to be done for this is simply removing the calls to `m.dump_stats()` in the scripts in `examples/`
