### ISSUE TITLE
Logging presets

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#431]
We should decide on the logging presets that Manticore will come configured with as a convenience logging interface. This will allow users to have coarse control over logging without having to deal directly with the python logging infrastructure.

We can possibly implement a second, fine grain logging interface later for users that desire more control than the presets allow.

**Comment by mossberg** [comment]
These are the logging semantics I propose:

0 (api default): warnings and errors only
1 (cli default): testcase generation messages, high level start/stop/stats info
2 -v: above, plus loader output, syscalls, state forking
3 -vv: above, plus instructions and emulation
4 -vvv: above, plus register values
5 -vvvv: above, plus smt.

**Comment by mossberg** [comment]
Here was a proposal from @yan (but yan, feel free to correct me or edit if I'm wrong)

nothing: no output or high level start/stop/stats info
-v: loader output, syscalls, state forking
-vv: above, plus instructions and emulation
-vvv: above, plus register values
-vvvv: above, plus memory/register access/updates

**Comment by mossberg** [comment]
@japesinator @feliam @yan can you all please weigh in on this? let's try to decide by the end of this week.

**Comment by feliam** [comment]
* I think the setting for the different -vvvv are cli/__main__ responsibility.
* set_verbosity must be out of the Manticore class as it is global
* it should(please!) handle easy granular settings not just pre-set numeric. So you don't need to copy paste logger.setLevel() to set your desired log setting. 
* We need to consider other logger naming setup. getLogger(__name__)?

**Comment by japesinator** [comment]
As an API consumer, I'd definitely like to have methods for both setting manticore to one of a few sensible presets and tweaking settings for individual loggers. I'm alright with either of the proposals above for default levels, but have a slight preference for the former. I also agree with pretty much all of Felipe's points above.

**Comment by mossberg** [comment]
> On Aug 3, 2017, at 9:43 AM, feliam <notifications@github.com> wrote:
> 
> I think the setting for the different -vvvv are cli/main responsibility.
We also need to consider the API here; API users should be able to use this convenience interface to help them debug their Manticore scripts. So I’d say the logic for setting these presets should exist in the core, and the cli should use the same interface for setting presets that a script would. 
> set_verbosity must be out of the Manticore class as it is global
Sure, this makes sense to me. I like how `m.verbosity` allows you to keep your imports minimal (`from manticore import Manticore` instead of `from manticore import Manticore, set_verbosity`), but having it has a global helper is more correct.
> it should(please!) handle easy granular settings not just pre-set numeric. So you don't need to copy paste logger.setLevel() to set your desired log setting.
I agree that this coarse preset interface shouldn’t be our *only* interface. I think we should also have granular settings, but I think that should be a separate discussion.
> We need to consider other logger naming setup. getLogger(name)?

Are there any considerations for this we need to make at this time, when deciding the semantics of the preset levels?

**Comment by feliam** [comment]
Oh right. preset levels. I was a bit off topic. Sorry about that.
Just reporting that based on my experience with it I won't be using the presets if I have another option.

**Comment by mossberg** [comment]
Ok, gotcha. Did you have any preference for either preset proposal?

**Comment by mossberg** [comment]
@yan thoughts on this?

**Comment by yan** [comment]
From my own use case, I tend to use `verbosity` much more than setting individual logger levels. Regarding what they mean, Mark's seems most reasonable.

@feliam, how do you typically use the individual log levels? I can see needing to set the SMT logger be debug while everything else is defaulted to critical. I usually do print-debugging if I'm doing anything non-standard :(

**Comment by mossberg** [comment]
Ok, it sounds like it’s decided: we will use the presets described here: https://github.com/trailofbits/manticore/issues/431#issuecomment-320023414

One thing is that those presets are slightly linux specific; for level 2, it should really be “platform logging” instead of “loader output, syscalls”
