### ISSUE TITLE
Automatically model dynamic symbols

### ISSUE THREAD

**Issue by offlinemark** [trailofbits/manticore#434]
If we are analyzing a dynamically linked binary, and we have models implemented for dynamic symbols it requires, we should automatically apply those models.

**Comment by yan** [comment]
This might bump symbol resolution in priority, since we'd need to do it anyway. This will also let us do things like:

```
@m.hook('strcpy')
def strcpy(state):
    state.invoke_model(models.strcpy)
```

**Comment by ehennenfent** [comment]
https://github.com/trailofbits/manticore/wiki/Ideas
