### ISSUE TITLE
Move individual syscall logging to dispatcher

### ISSUE THREAD

**Issue by yan** [trailofbits/manticore#440]
We currently have syscalls log themselves, which is repetitive and can leave out some invocations. We should move the `logger.debug` line to the syscall dispatcher to standardize on format and be consistent.

**Comment by johnfxgalea** [comment]
Can I ask for more information related to this issue. A prototype of the dispatch function, with its parameters listed, would be great.

**Comment by mossberg** [comment]
This doesn't answer the above question, but an additional note, this would likely be a modification of `Linux.syscall`. it might be tricky to obtain the syscall arguments outside the syscall function though, because they need to be extracted from the State. This is what the syscall abi does.

**Comment by mossberg** [comment]
another consideration is that certain syscalls have special debug output (mmap)

**Comment by yan** [comment]
@johnfxgalea, this issue isn't as trivial as it should be. The ABI implementation currently reads arguments from the calling environment in a stream-based manner[1], which makes it more difficult to log arguments. One way I was considering doing this earlier is to wrap the model again with a logged version, but you'd need to wrap with a model of identical arity.

[1] https://github.com/trailofbits/manticore/blob/master/manticore/core/cpu/abstractcpu.py#L303-L314
