### ISSUE TITLE
save_stream() got an unexpected keyword argument 'binary'

### ISSUE THREAD

**Issue by hrdn** [trailofbits/manticore#446]
### OS / Environment

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

### Python version

Python 2.7.12

### Summary of the problem
i got error save_stream() got an unexpected keyword argument 'binary'

### Step to reproduce the behavior
I tried this script 
https://github.com/trailofbits/manticore-examples/blob/master/google2016_unbreakable/win.py

**Comment by yan** [comment]
Are you running manticore from github or from pypi? Can you include the stack trace?

**Comment by mossberg** [comment]
Our manticore-examples CI passed earlier today, so it's odd that win.py would break https://travis-ci.org/trailofbits/manticore-examples/builds/262819924

**Comment by mossberg** [comment]
@japesinator was this fixed in #396 ?

**Comment by japesinator** [comment]
It was
