### ISSUE TITLE
Add a REGISTRAR of plugins to manticore main api.

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#457]
A plugin could look like: 

    class plugin():
        name = "TRACER"
        depends_on = ()
        def on_init_state(state):
            state.context['trace'] = []
        
        def on_will_execute_instruction(state):
            state.context['trace'].append( state.current.PC
    manticore.register(plugin())

Then register() function look for methods in plugin() which names start with "on_" and subscribe them to the correct event. on_will_execute_instruction() with 'will_excecute_instruction'

**Comment by mossberg** [comment]
One concern I have about this is that I don't think it's good to have an API so heavily based on strings ('will_execute_instruction') vs other more appropriate types (some sort of enum/int thing?), and this specific idea builds heavily on this "stringly-typed" API.

**Comment by feliam** [comment]
I like very much the fact we don't need to declare or import anything to consume events.
And a little less that you don't need to do anything extra to emit new events.

What's the drawback of string == event ? 
Someone could misspell the event name?
The user won't know what all the events are?
We can overcome those by having the list of all known string events (basically an enumeration) in Events.py. Then subscribe/publish can just check for valid event.

**Comment by feliam** [comment]
>>> a = "LALA"
>>> b = "LALA"
>>> id(a)
139713395722544
>>> id(b)
139713395722544

**Comment by japesinator** [comment]
How do we feel about a plugin class that has a decorator for subscribing callbacks to signals, e.g.

```
@manticore.subscribe('will_execute_instruction')
def on_will_execute_instruction(state):
    state.context['trace'].append( state.current.PC
```

**Comment by feliam** [comment]
Not sure how that works. We need son syntactic sugar for

    plugin_instanse = SomePlugin()
    m=Manticore()
    m.subscribe('will_execute_instruction', plugin_instance.on_will_execute_instruction)

**Comment by nettrino** [comment]
I also agree on heavily using syntastic sugar for this. Even 
```
@manticore.subscribe('will_execute_instruction')
def on_will_execute_instruction(state):
```
seems too cumbersome. I also agree with mark on using enumerations. User's don't need to explicitly set their plugin names etc. As soon as it inherits from a certain class, we will know the
functionality as well as its name from the class name. E.g., 

```
class MyPlugin(ExecutorPlugin):
    @on_instruction
     blah

    @on_other
    ...
```

**Comment by feliam** [comment]
So the plugin class will provide the decorators. Some methods will be labeled with the event name (instead of just using a specific name). Then on m.register(plugin) it will find the correct event for the correct method and subscribe ?

**Comment by mossberg** [comment]
going to close this. we have fairly firmly gone in the direction of registering callback handlers using `def <event_name>_callback()` (e.g. `def will_evm_execute_instruction_callback()`) at this point.
