### ISSUE TITLE
Automated Docker Build

### ISSUE THREAD

**Issue by Owlz** [trailofbits/manticore#463]
Many of us like to use Docker to keep things clean and updated. It would be nice if Manticore had an automated Docker build on dockerhub.

**Comment by randomlshb** [comment]
There is a Dockerfile ready to go, but it isn't on Docker Hub.

```
git clone https://github.com/trailofbits/manticore
cd manticore
docker build -t manticore .
```

```
$ docker run -it manticore
manticore@324c658021ff:~$ python 
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import manticore
>>> dir(manticore)
['Manticore', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'binary', 'core', 'issymbolic', 'manticore', 'models', 'platforms', 'utils', 'variadic']
```

**Comment by ctfhacker** [comment]
There is already a Dockerfile for manticore, but it isn't in Docker Hub.

```
git clone https://github.com/trailofbits/manticore
cd manticore
docker build -t manticore .
```

```
$ docker run -it manticore
manticore@324c658021ff:~$ python 
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import manticore
>>> dir(manticore)
['Manticore', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'binary', 'core', 'issymbolic', 'manticore', 'models', 'platforms', 'utils', 'variadic']
```

Depending on what is needing analysis, a share might be needed to bring external files into the Docker:

```
$ docker run -v /home/ctfhacker/ctfs:/home/manticore/host-share -it manticore
manticore@c439ecf64e0d:~$ ls
host-share
```

In this way, binaries can be dropped in `/home/ctfhacker/ctfs` on the host machine and accessed in the `/home/manticore/host-share` directory in the Docker.

**Comment by Owlz** [comment]
Yep. It's just nice not having to git clone and build. Super easy to add an automated build on docker hub. Unfortunately, i haven't found a way to tell docker hub to monitor someone else's github for builds. It appears it needs to link to your account to provide the automated git monitoring and building.

**Comment by mossberg** [comment]
@japesinator could you look into setting up the automated build for this?

**Comment by japesinator** [comment]
I actually have had a build at https://hub.docker.com/r/japesinator/manticore/ for a while now, it just isn't advertised (mostly because it's not actively used or tested). If that doesn't work for you, feel free to open another issue about making a more "official"/supported one

**Comment by Owlz** [comment]
@japesinator  i don't think your automated build is working. The last build was 3 months ago for the Docker image. The last push to github was 3 days ago. And there have been many changes in between.

The goal of this issue is to create an automated Docker build that we can simply pull and it will be the very latest. That is not the case with your image.

**Comment by japesinator** [comment]
Hmm, that's weird, let me take a look at it today and see if I can get it working

**Comment by Owlz** [comment]
For what it's worth, i have noticed that sometimes the "perform automated build on github push" checkbox thing is actually backwards. To get it to build, sometimes you have to uncheck it *shrug*

**Comment by japesinator** [comment]
That's kind of bizarre, but I'll try it

**Comment by Owlz** [comment]
Also -- just figured out that you have to link up your account to fully permissions (not limited) on github to be able to auto-build. Oddly enough, Docker doesn't give you an error or anything when this isn't the case.

**Comment by mossberg** [comment]
I just created an official automated build here: https://hub.docker.com/r/trailofbits/manticore/
