### ISSUE TITLE
command-line symbolic argv?

### ISSUE THREAD

**Issue by Owlz** [trailofbits/manticore#464]
I've been having trouble getting command-line symbolic argv to work. For instance:

```bash
$ manticore ./test AAAAAAAAAAAAAAAAA
```

The "A" values do not appear to become symbolic. Nor does the argv[0] ("./test") string.

**Comment by feliam** [comment]
I don't think you can make argv[0] symbolic from the command line. For that you'll need to dig into the API. 
As for argv[N+1] you can do something like this ...

manticore ./test +++++++++++++++

'+' will be replaced by free symbolic bytes.

**Comment by Owlz** [comment]
Ah, you're right the + worked for that. Could also be useful to have argv[0] be symbolic as well. My guess is to accomplish that you would actually need a flag on the command line, like --symbolic-argv [N [N] [N]].

**Comment by mossberg** [comment]
symbolic arg[0] is an interesting thought, but i can't say it feels like a common use case to me. it would be possible currently from the API by hooking and overwriting argv[0] with a `State.new_symbolic_buffer()`

since the original question seemed to be answered, going to close
