### ISSUE TITLE
Remove unneeded code from Cpu.execute

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#474]
Quite simply, this can be removed, as it no longer applies.

https://github.com/trailofbits/manticore/blob/ca0d7b60d206a7f159694721317034ad49eae666/manticore/core/cpu/abstractcpu.py#L722-L724

Discussion here: https://github.com/trailofbits/manticore/pull/467#discussion_r134544511

**Comment by endeav0r** [comment]
I will give this a look this weekend.

**Comment by mossberg** [comment]
Apparently this is not so trivial after all; removing this code causes a test to fail and actually changes execution.

**Comment by mossberg** [comment]
would be nice to debug this to understand why exactly tests fail if it's removed. then we should replace the question comment with an explanation comment

**Comment by mossberg** [comment]
old and likely won't get to
