### ISSUE TITLE
Time to process initialisation code adds a significant delay to the dev <-> test cycle

### ISSUE THREAD

**Issue by SeanHeelan** [trailofbits/manticore#522]
### OS / Environment
Fedora 25, Kernel 4.3.5, x86_64

### Manticore version
0.1.4 (git master head)

### Python version
2.7.13

### Dependencies
alabaster==0.7.10
Babel==2.5.1
backports.shutil-get-terminal-size==1.0.0
capstone==3.0.5rc2
certifi==2017.7.27.1
chardet==3.0.4
coverage==4.4.1
decorator==4.1.2
docutils==0.14
enum34==1.1.6
idna==2.6
imagesize==0.7.1
ipdb==0.10.3
ipython==5.5.0
ipython-genutils==0.2.0
Jinja2==2.9.6
keystone-engine==0.9.1.post3
-e git+https://github.com/trailofbits/manticore.git@e84c0513a2d850e3fe63bd23425d7ba67a88c7dc#egg=manticore
MarkupSafe==1.0
nose==1.3.7
pathlib2==2.3.0
pexpect==4.2.1
pickleshare==0.7.4
ply==3.10
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pyelftools==0.24
Pygments==2.2.0
pytz==2017.2
redis==2.10.6
requests==2.18.4
scandir==1.6
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.4
sphinxcontrib-websupport==1.0.1
traitlets==4.3.2
typing==3.6.2
unicorn==1.0.1
urllib3==1.22
wcwidth==0.1.7
z3-solver==4.5.1.0.post2

### Summary of the problem

While testing on a simple target program it takes about 1m35s to reach the `main` function. Most of this time seems to be spent loading libc and I get similar behavior regardless of whether I use the API programatically or via the `manticore` tool. 

The main issue with this is that it makes iterative development of a script based on manticore quite painful as every run has an overhead of at least 1m30s, regardless of how complex the target is. 

### Step to reproduce the behavior

Timing script: 
```
#!/usr/bin/env python

import sys
import time

from manticore import Manticore

# The address of the main() function
MAIN_ADDR = 0x4005b6
start_time = time.time()
m = Manticore(sys.argv[1])

@m.hook(MAIN_ADDR)
def log_msg(state):
    print "Reached main after %f seconds" % (time.time() - start_time)
    m.terminate()

m.run(procs=1)
```

Test program:
```
#include <stdio.h>
#include <string.h>

int main(int argc, char *argv[])
{
    if (argc != 2) {
        printf("Key not provided\n");
        return 1;
    }

    if (!strcmp(argv[1], "VTX")) {
        printf("KEY FOUND\n");
    } else {
        printf("Incorrect key: %s\n", argv[1]);
    }
    return 0;
}
```

### Expected behavior

I understand this isn't a bug as much as it's a factor of `time_per_instruction * num_instructions_before_main`. Is there something I am missing with regards to this sort of work flow which would allow a more rapid dev <-> test cycle? 

Issues https://github.com/trailofbits/manticore/issues/70 and https://github.com/trailofbits/manticore/issues/415 appear related.

**Comment by yan** [comment]
Thanks for the report!

I can suggest two courses of action. First, if it's just for testing, you can compile your binary as a static executable, which should speed up things significantly. Your script, just modified to take address of main from the command line:
```
user@host:manticore$ gcc vtx.c -o vtx && python 522.py vtx `nm vtx | grep 'T main' | awk '{print $1}'`
Reached main after 73.475680 seconds
user@host:manticore$ gcc vtx.c -static -o vtx && python 522.py vtx `nm vtx | grep 'T main' | awk '{print $1}'`
Reached main after 5.636049 seconds
```

The other option is to use a a presently private API from `master` for explicit state saving/loading.

```
user@host:manticore$ python 522.py vtx 4005b6
Reached main after 62.579031 seconds
user@host:manticore$ python 522.py vtx 4005b6
Reached main after 0.119980 seconds
```
Where 522.py is:

```python
#!/usr/bin/env python

import os
import sys
import time
import cPickle

from manticore import Manticore

saved_state = 'just_after_main.state'

MAIN_ADDR = int(sys.argv[2], 16)
start_time = time.time()
m = None
if os.path.exists(saved_state):
    with open(saved_state, 'rb') as f:
        m = Manticore(cPickle.load(f))
else:
    m = Manticore(sys.argv[1])


@m.hook(MAIN_ADDR)
def log_msg(state):
    print "Reached main after %f seconds" % (time.time() - start_time)
    with open(saved_state, 'wb') as f:
        f.write(cPickle.dumps(state, 2))
    m.terminate()

m.run(procs=1)
```

**Comment by SeanHeelan** [comment]
Ah, nice. Thanks for the quick response!
