### ISSUE TITLE
cannot import evm module 

### ISSUE THREAD

**Issue by AlexXiong97** [trailofbits/manticore#523]
### OS / Environment
Ubuntu 16.04 LTS

### Manticore version
0.1.4

### Python version
2.7 (virtualenv contained environment)

### Dependencies
boto==2.48.0
capstone==3.0.5rc2
manticore==0.1.4
ply==3.10
pyelftools==0.24
pysha3==1.0.2
unicorn==1.0.1
z3-solver==4.5.1.0.post2

### Summary of the problem
1.  When trying to run `example/evm` python files, following error was raised:
```shell 
 from manticore.platforms import evm
ImportError: cannot import name evm
```
This is due to in `evm\seth.py` line 4 was trying to import a python file named `evm.py`, but there is no class or module called evm inside any files, similarly on line5, `from manticore.platforms.evm import pck_msb` would throw a `module not found` error 

2. Another minor issue, is in the README.md, 
when i tried to install by running `python setup.py install`, all dependencies were added as expected, but the command `manticore *fileName*`would still throw `Z3NotFound` error, which is caused by no Z3 command under /bin. I solved it by running `sudo pip install z3-solver` which add z3 to my `usr/local/bin/z3` (without sudo, it doesn't work) 

Not sure this minor error was only because of my wrong-operation or missing steps during installation, but just to raise out for your knowledge. 

Thanks!

**Comment by yan** [comment]
@AlexXiong97, can you try again using our most recent release (0.1.5)?
