### ISSUE TITLE
evm: swarm hash in bytecode misinterpreted as INVALID opcode

### ISSUE THREAD

**Issue by alxiong** [trailofbits/manticore#527]
Essence of the issue emerges from **post 0.4.7** solidity compiler appends swarm hashes at the end of the deployed compiled bytecode. 

[See official 0.4.7 major release summary:]( https://github.com/ethereum/solidity/releases/tag/v0.4.7)

Namely, normally actual bytecode ends with `5600` or equivalently `Jump`, `Stop` or equivalently "Alter the program counter, then halts execution"
After this, a following pattern should be observed _(post 0.4.7 of course)_:
`a165627a7a72305820` +<32bytes swarm hash> + '0029' 

[See solc bytecode metadata documentation](http://solidity.readthedocs.io/en/develop/metadata.html?highlight=swarm#encoding-of-the-metadata-hash-in-the-bytecode) 

Currently, in evm examples, all `coverage.log` recognize the metadata as INVALID opcode, or misinterpret them if case of collisions (i.e. "a1" used here doesn't translate to "Log 1 item"). To discuss in a more specific case, running
`python simple_mapping.py`
terminal output ends with:
```shell
  0x01b3 <56> JUMP                                                                       Alter the program counter.
   0x01b4 <00> STOP                                                                       Halts execution.
   0x01b5 <a1> LOG1                                                                       Append log record with one topic.
   0x01b6 <65627a7a723058> PUSH6 0x627a7a723058                                           Place 6-byte item on stack.
   0x01bd <20> SHA3                                                                       Compute Keccak-256 hash.
   0x01be <cd> INVALID                                                                    Unknown opcode
   0x01bf <7423ee0b5f90785ff9114882a877fcb42f9b90a142c9> PUSH21 0x23ee0b5f90785ff9114882a877fcb42f9b90a142c9Place 21-byte item on stack.
   0x01d5 <28> INVALID                                                                    Unknown opcode
   0x01d6 <21> INVALID                                                                    Unknown opcode
   0x01d7 <d7> INVALID                                                                    Unknown opcode
   0x01d8 <0b> SIGNEXTEND                                                                 Extend length of two's complement signed integer.
   0x01d9 <dc> INVALID                                                                    Unknown opcode
   0x01da <3f> INVALID                                                                    Unknown opcode
   0x01db <a9> INVALID                                                                    Unknown opcode
   0x01dc <10> LT                                                                         Less-than comparision.
   0x01dd <a4> LOG4                                                                       Append log record with four topics.
   0x01de <00> STOP                                                                       Halts execution.
   0x01df <29> INVALID                                                                    Unknown opcode
Total assembler lines: 188
Total assembler lines visited: 108
Coverage: 57.45%
```

Two Problems attributed to this misinterpretation:
1. coverage log is not entirely correct. 
2. coverage rate is incorrect since `total assembler lines` take swarm hash bytecode into account, which is inaccurate, while `total assembler lines visited` is accurate, resulting in a lower than actual coverage. 

Proposed Solution:
1. add solidity compiler version pattern search in `contract_source_code` 
2. add a pattern regex search and slice the opcode before passing into the `EVMDecoder.table`  (https://github.com/trailofbits/manticore/blob/master/manticore/platforms/evm.py#L479)

Reference:
A bytecode verifier tool. (https://www.npmjs.com/package/eth-bytecode-verifier)
Its source code will be public soon. But the idea and observation borrows from that tool.

**Comment by AlexXiong97** [comment]
One more suggestion for update:

Provide EVM support for Byzantium hard fork:
specifically:
4 new EVM opcodes:
-- 0xFD REVERT : introduced in 0.4.10 with "require()" vs. previous "throw" or "assert". Revert opcode does revert all the states AND return remaining gas, compared to "throw" who consumes all the gas in an fictitious loop. 
-- 0x3D RETURNDATASIZE : similar to CALLDATASIZE, just extends to return data as well. This enables nice error messages.
-- 0x3E RETURNDATACOPY : similar to CALLDATACOPY, extends to return data. 
-- 0xFA STATICCALL : explicit opcode to distinguish read-only operation/query and write operations, to mitigate possible re-entrancy bug

Thanks!

**Comment by mossberg** [comment]
hi @AlexXiong97, thanks a lot for this issue, sort for responding so late 😓  we'll definitely take this into account soon!
