### ISSUE TITLE
expression.Array assertion failure if index_max is a long instead of an int

### ISSUE THREAD

**Issue by SeanHeelan** [trailofbits/manticore#536]
### OS / Environment
Fedora 25

### Manticore version
0.1.4 

### Python version
2.7.14

### Dependencies
alabaster==0.7.10
Babel==2.5.1
backports.shutil-get-terminal-size==1.0.0
capstone==3.0.5rc2
certifi==2017.7.27.1
chardet==3.0.4
coverage==4.4.1
decorator==4.1.2
docutils==0.14
enum34==1.1.6
idna==2.6
imagesize==0.7.1
ipdb==0.10.3
ipython==5.5.0
ipython-genutils==0.2.0
Jinja2==2.9.6
keystone-engine==0.9.1.post3
-e git+https://github.com/trailofbits/manticore.git@e84c0513a2d850e3fe63bd23425d7ba67a88c7dc#egg=manticore
MarkupSafe==1.0
nose==1.3.7
pathlib2==2.3.0
pexpect==4.2.1
pickleshare==0.7.4
ply==3.10
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pyelftools==0.24
Pygments==2.2.0
pytz==2017.2
redis==2.10.6
requests==2.18.4
scandir==1.6
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.4
sphinxcontrib-websupport==1.0.1
traitlets==4.3.2
typing==3.6.2
unicorn==1.0.1
urllib3==1.22
wcwidth==0.1.7
z3-solver==4.5.1.0.post2

### Summary of the problem

If `state.new_symbolic_buffer(x)` is called and `x` is a long instead of an int then an assertion in `expression.Array` fails. 

### Step to reproduce the behavior

Utilise `state.invoke_model` to trigger a model of a function that takes a numeric argument. The argument reaches the model as a long, not an int. If the model then uses this argument in a call to `new_symbolic_buffer` the assertion failure occurs.

```
# Hook for function with the following signature 
# size_t read_data(const char *fname, char *dest, size_t count) 
def read_data(state, fname, dest, count):
    print "Introducing %d symbolic bytes at 0x%x" % (count, dest)
    buf = state.new_symbolic_buffer(count)
    state.cpu.write_bytes(dest, buf)
    with m.locked_context() as ctx:
        ctx['input_addr'] = dest

    return count

@m.hook(READ_DATA)
def read_data_model(state):
    print "Invoking model for read_data"
    state.invoke_model(read_data)
```

### Expected behavior

Either the model invocation should provide the arguments to the model as an int, or the expression creation code should not be fussy about whether it receives an int or a long. I wasn't sure which is more desirable in terms of manticore's design, hence no pull request =)

**Comment by mossberg** [comment]
Sean, thanks a lot for the issue! I've opted for the former of your suggestions, and corrected other places in the code where the similar buggy pattern is used.
