### ISSUE TITLE
IOError (Illegal seek) when saving a state

### ISSUE THREAD

**Issue by SeanHeelan** [trailofbits/manticore#537]
### OS / Environment
Fedora 25

### Manticore version
0.1.4

### Python version
2.7.14

### Dependencies
alabaster==0.7.10
Babel==2.5.1
backports.shutil-get-terminal-size==1.0.0
capstone==3.0.5rc2
certifi==2017.7.27.1
chardet==3.0.4
coverage==4.4.1
decorator==4.1.2
docutils==0.14
enum34==1.1.6
idna==2.6
imagesize==0.7.1
ipdb==0.10.3
ipython==5.5.0
ipython-genutils==0.2.0
Jinja2==2.9.6
keystone-engine==0.9.1.post3
-e git+https://github.com/trailofbits/manticore.git@e84c0513a2d850e3fe63bd23425d7ba67a88c7dc#egg=manticore
MarkupSafe==1.0
nose==1.3.7
pathlib2==2.3.0
pexpect==4.2.1
pickleshare==0.7.4
ply==3.10
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pyelftools==0.24
Pygments==2.2.0
pytz==2017.2
redis==2.10.6
requests==2.18.4
scandir==1.6
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.4
sphinxcontrib-websupport==1.0.1
traitlets==4.3.2
typing==3.6.2
unicorn==1.0.1
urllib3==1.22
wcwidth==0.1.7
z3-solver==4.5.1.0.post2

### Summary of the problem

The target program contains a double free, which is detected by libc. During the processing of the code libc invokes to terminate the process on such an event manticore raises an IOError that looks as follows (the full log is linked below):

```
2017-10-27 15:33:28,749: [30775] m.c.executor:ERROR: Exception: [Errno 29] Illegal seek
Traceback (most recent call last):
  File "/home/user/git/manticore/manticore/core/executor.py", line 472, in run
    self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/home/user/git/manticore/manticore/core/executor.py", line 405, in fork
    state_id = self.enqueue(new_state)
  File "/home/user/git/manticore/manticore/core/executor.py", line 258, in enqueue
    state_id = self._workspace.save_state(state)
  File "/home/user/git/manticore/manticore/core/workspace.py", line 393, in save_state
    self._store.save_state(state, '{}{:08x}{}'.format(self._prefix, id_, self._suffix))
  File "/home/user/git/manticore/manticore/core/workspace.py", line 153, in save_state
    self._serializer.serialize(state, f)
  File "/home/user/git/manticore/manticore/core/workspace.py", line 43, in serialize
    f.write(cPickle.dumps(state, 2))
  File "/home/user/git/manticore/manticore/platforms/linux.py", line 52, in __getstate__
    state['pos'] = self.tell()
  File "/home/user/git/manticore/manticore/platforms/linux.py", line 78, in tell
    return self.file.tell(*args)
IOError: [Errno 29] Illegal seek
```

### Step to reproduce the behavior
Compile the following via `gcc -static -o test_double_free test_double_free.c` and run with `manticore -v --procs=5 test_double_free +`

```
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

void safe(void)
{
    char *p = malloc(100);
    char *v = malloc(200);

    printf("%p %p\n", p, v);

    free(v);
    free(p);
}

void unsafe(void)
{
    char *p = malloc(100);
    char *v = malloc(200);

    printf("%p %p\n", p, v);

    free(v);
    free(p);
    // Bug
    free(p);
}

int main(int argc, char *argv[])
{
    if (argc != 2) {
        printf("Usage: %s X\n", argv[0]);
        printf("\t\tX: 1 for safe, 2 for unsafe\n");
        return 1;
    }

    if (!strcmp(argv[1], "1")) {
        safe();
    } else if (!strcmp(argv[1], "2")) {
        unsafe();
    } else {
        printf("Invalid command\n");
        return 1;
    }
    return 0;
}
```

### Actual behavior

After a minute or so an IOError exception is raised. The full log can be found here https://pastebin.com/936W3Frv

**Comment by SeanHeelan** [comment]
It might just be to do with generic error handling in libc, rather than anything specific to double-frees as this program also triggers it (the bug in this case being that the free'd pointers are not base pointers).

```
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

void safe(void)
{
    char *p = malloc(100);
    char *v = malloc(200);

    printf("%p %p \n", p, v);

    free(p);
    free(v);
}

void unsafe1(void)
{
    char *p = malloc(100);
    char *v = malloc(200);

    printf("%p %p\n", p, v);

    free(p);
    // Bug
    free(v + 1);
}

void unsafe2(void)
{
    char *p = malloc(100);
    char *v = malloc(200);

    printf("%p %p\n", p, v);

    free(p);
    // Bug
    free(v - 1);
}

int main(int argc, char *argv[])
{
    if (argc != 2) {
        printf("Usage: %s X\n", argv[0]);
        printf("\t\tX: 1 for safe, 2 for unsafe1, 3 for unsafe2\n");
        return 1;
    }

    if (!strcmp(argv[1], "1")) {
        safe();
    } else if (!strcmp(argv[1], "2")) {
        unsafe1();
    } else if (!strcmp(argv[2], "3")) {
        unsafe2();
    } else {
        printf("Invalid command\n");
        return 1;
    }
    return 0;
}
```

**Comment by mossberg** [comment]
thanks for the issue!

The specific issue that caused the IOError was due to `/dev/tty` being opened at some point. Our code for saving and restoring state used `file.tell()` to save the file position, which caused the IOError crash when that was called on the `/dev/tty` file object. Even with the fix, it seems Manticore does not correct make it to the end of the program, but reports an invalid memory access in `__libc_malloc` which I suspect is wrong :/ We'll need to look into that also.

```
2017-11-13 18:35:25,537: [67131] m.c.c.abstractcpu:DEBUG: INSTRUCTION: 0x000000000041dc31:  lea rax, qword ptr [rdx - 0x10]
2017-11-13 18:35:25,539: [67131] m.c.c.abstractcpu:DEBUG: INSTRUCTION: 0x000000000041dc35:  and rax, 0xfc000000
2017-11-13 18:35:25,541: [67131] m.c.c.abstractcpu:DEBUG: INSTRUCTION: 0x000000000041dc3b:  mov rcx, qword ptr [rax]
2017-11-13 18:35:26,227: [67131] m.manticore:INFO: Generated testcase No. 0 - Invalid memory access (mode:r) <f8000000>
2017-11-13 18:35:26,248: [67131] m.manticore:INFO: Results in /mnt/hgfs/code/manticore/examples/linux/mcore_NzXjgF
2017-11-13 18:35:26,249: [67131] m.manticore:INFO: Total time: 149.902643919
```
