### ISSUE TITLE
KeyError accessing the global storage in SLOAD

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#543]
### OS / Environment
ArchLinux

### Manticore version

baf2d769a624306f91fcca44bcff0b087f1bba69

### Python version

2.7

### Summary of the problem

KeyError accessing the global storage in SLOAD

### Step to reproduce the behavior

I'm using [this script](https://gist.github.com/ggrieco-tob/3f3491956197e8ba19f88694af803bab) to test manticore.

$ ./evm.py [QuickFuzz.80617981580.352.5119381167503483594.150.evm.txt](https://github.com/trailofbits/manticore/files/1423626/QuickFuzz.80617981580.352.5119381167503483594.150.evm.txt)

### Expected behavior

It shouldn't crash.

### Actual behavior

Traceback (most recent call last):
  File "./evm.py", line 27, in <module>
    evm.execute() 
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 841, in execute
    result = implementation(*arguments)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 1210, in SLOAD
    return self.global_storage[self.address]['storage'][offset]
KeyError: 71748523475265

**Comment by mossberg** [comment]
going to close for now, that script shows kind of an old way of using mcore evm
