### ISSUE TITLE
Add EVM details to "Hacking on Manticore"

### ISSUE THREAD

**Issue by dguido** [trailofbits/manticore#580]
We should add some tips for contributing EVM-related code on the wiki, in particular on this page:

https://github.com/trailofbits/manticore/wiki/Hacking-on-Manticore

**Comment by mossberg** [comment]
Did you have any specific ideas in mind?

cc @feliam

**Comment by feliam** [comment]
* Adding instructions is pretty trivial. We could explain how to add one. There are not many left to implement though.
* The "syscalls" here would be the block/world access. How to hack that is not yet clear even for us. Refactor alert!
* We could show how to add a high level example? And describe the API, wip. 
* We could show how to add an instruction unittest

-- There is a blog post like explanation of some of the examples/evm/ in the works. (Not sure how far will that get. It can be demoted to a wikipage)

**Comment by mossberg** [comment]
The evm code will be highly in flux in the coming months as we address tech debt, and refactor. Any dev documentation for evm will quickly become out of date so i'm removing this from 0.1.6. once the code is more stable, we'll do this

**Comment by mossberg** [comment]
closing this for now, not exactly clear what content should be added
