### ISSUE TITLE
testBasicUnmapping assertion error for parallel nosetests

### ISSUE THREAD

**Issue by cole-lightfighter** [trailofbits/manticore#600]
### OS / Environment
4.13.12-1-ARCH GNU/Linux

### Manticore version
Version: 0.1.5

### Python version
Python 2.7.14

### Dependencies
alabaster==0.7.10
asn1crypto==0.22.0
attrs==17.2.0
autobahn==17.8.1
Automat==0.6.0
Babel==2.5.1
bcrypt==3.1.3
beautifulsoup4==4.6.0
capstone==3.0.5rc2
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
cmd2==0.7.6
constantly==15.1.0
coverage==4.4.2
crochet==1.9.0
cryptography==2.0.3
docutils==0.14
enum34==1.1.6
hyperlink==17.3.1
idna==2.5
imagesize==0.7.1
incremental==17.5.0
intervaltree==2.1.0
ipaddress==1.0.18
Jinja2==2.9.6
keystone-engine==0.9.1.post3
lxml==3.8.0
Mako==1.0.7
-e git+https://github.com/trailofbits/manticore@0e4e9a49e2dcab5651d74fbbd8de4649428efa4c#egg=manticore
MarkupSafe==1.0
nose==1.3.7
packaging==16.8
paramiko==2.2.1
Parsley==1.3
pluggy==0.4.0
ply==3.10
psutil==5.2.2
pwntools==3.8.0
py==1.4.34
pyasn1==0.3.2
pyasn1-modules==0.0.11
pycparser==2.18
pyelftools==0.24
Pygments==2.2.0
PyNaCl==1.1.2
pyOpenSSL==17.2.0
pypandoc==1.4
pyparsing==2.2.0
pyperclip==1.5.27
pyserial==3.4
pysha3==1.0.2
PySocks==1.6.7
pytest==3.2.4
python-dateutil==2.6.1
pytz==2017.3
redis==2.10.6
requests==2.18.3
ROPGadget==5.4
scrypt==0.8.0
service-identity==17.0.0
six==1.10.0
snowballstemmer==1.2.1
sortedcontainers==1.5.7
Sphinx==1.6.5
sphinxcontrib-websupport==1.0.1
tox==2.7.0
Twisted==17.5.0
txaio==2.8.1
txsocksx==1.15.0.2
typing==3.6.2
unicorn==1.0.1
urllib3==1.22
virtualenv==15.1.0
wrapt==1.10.11
z3-solver==4.5.1.0.post2
zope.interface==4.4.2

### Summary of the problem

Ran into a memory corruption or potential data race, can't quite tell.
No error occurs when running with 8 (or fewer?) processes, but running
with 10 processes produces the memory error (two lists should be equal,
but RHS list is missing a member).

### Step to reproduce the behavior
The below `nosetests` command reliably produces the same memory error.

```
nosetests --processes=10 --process-timeout=120
```

### Expected behavior
RHS list should match the LHS list.

### Actual behavior
The RHS list is missing what should be its third member, i.e.  it should be `[3, 4, 5, 6]`

### Any relevant logs
```
======================================================================
ERROR: testBasicUnmapping (tests.test_memory.MemoryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/projects/manticore/tests/test_memory.py", line 39, in tearDown
    self.assertEqual(self.fds, self.get_open_fds())
AssertionError: Lists differ: [3, 4, 5, 6] != [3, 4, 6]

First differing element 2:
5
6

First list contains 1 additional elements.
First extra element 3:
6

- [3, 4, 5, 6]
?        ---

+ [3, 4, 6]

----------------------------------------------------------------------
Ran 8703 tests in 46.612s

FAILED (SKIP=4, errors=1)
```

**Comment by mossberg** [comment]
Thanks for reporting! I'm not exactly sure when we'll be able to get to this; in the mean time, you should be able to use non-parallel nosetests!

**Comment by cole-lightfighter** [comment]
No problem :)

I'll dig at it a little. Not really a critical issue, and parallel tests still work with fewer processes.  Thanks for the quick response!
