### ISSUE TITLE
workspace: rename *.txt file to *.inputs

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#618]
In the mcore workspace, the generated `.txt` files, contain concretized symbolic inputs.

https://github.com/trailofbits/manticore/blob/77b0542b83bce9695aa79d7447aa58f5c056b111/manticore/core/workspace.py#L531-L534

An improved extension for this file would be `.inputs` which is more intuitive and clear.

this is a backwards incompatible interface change.

**Comment by mossberg** [comment]
totally open to suggestions for other names.  `.input` ?

**Comment by yan** [comment]
`input` is good. Other options are `values` (not all expressions are inputs and can be symbolicated), `solutions`, and `expressions`.

**Comment by mossberg** [comment]
decision: `.input` file extension. ready for implementation.
