### ISSUE TITLE
workspace: emit workspace files in standard, but human readable serialization format

### ISSUE THREAD

**Issue by offlinemark** [trailofbits/manticore#620]
Manticore's analysis results are emitted to a workspace directory, with a number of files for each generated state (Example below). Some of these files have an ad hoc format that is human readable, for example:

*.txt
```
STDIN_1: '\x01\x01\x01\x01\x00\x00\x00\xc0\x01\x01\
```

It's conceivable that users may want to process these output files with code, though. Currently, they need to write their own parsers. While not hard, they should not have to.

Standard serialization formats exist which are designed for human readability (e.g. http://yaml.org/). When appropriate, Manticore should formally emit its workspace files in one of these formats.

This will be a backward incompatible interface change.

Specifically, I see no reason not to use yaml. It is quite human readable, stable, extensively used, and has wide support in programming languages.

---

```
-rw-r--r-- 1 501 dialout     44 Dec  1 13:28 command.sh
-rw-r--r-- 1 501 dialout   1238 Dec  1 13:28 test_00000000.messages
-rw-r--r-- 1 501 dialout      0 Dec  1 13:28 test_00000000.net
-rw-r--r-- 1 501 dialout 414563 Dec  1 13:28 test_00000000.pkl
-rw-r--r-- 1 501 dialout   2916 Dec  1 13:28 test_00000000.smt
-rw-r--r-- 1 501 dialout      0 Dec  1 13:28 test_00000000.stderr
-rw-r--r-- 1 501 dialout     12 Dec  1 13:28 test_00000000.stdin
-rw-r--r-- 1 501 dialout      0 Dec  1 13:28 test_00000000.stdout
-rw-r--r-- 1 501 dialout    927 Dec  1 13:28 test_00000000.syscalls
-rw-r--r-- 1 501 dialout  44032 Dec  1 13:28 test_00000000.trace
-rw-r--r-- 1 501 dialout   1036 Dec  1 13:28 test_00000000.txt
```

**Comment by ehennenfent** [comment]
https://github.com/trailofbits/manticore/wiki/Ideas
