### ISSUE TITLE
evm: Incorrect handling of div by zero in mulmod

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#648]
https://github.com/trailofbits/manticore/blob/591d7b81d56dae88c441975e955fece9f489ff58/manticore/platforms/evm.py#L1407

We catch div by zero here and silently return zero. I feel like this isn't correct; what does the evm do?

**Comment by yan** [comment]
geth treats a divbyzero as producing a 0, ¯\_(ツ)_/¯ [1]

[1] https://github.com/ethereum/go-ethereum/blob/master/core/vm/instructions.go#L66-L99

**Comment by feliam** [comment]
I'm going to close this. As this is how it is specified in the yellow and also how other VMs implement it.
