### ISSUE TITLE
Reintroduce Manticore.workspace property

### ISSUE THREAD

**Issue by yan** [trailofbits/manticore#672]
We have lost the `Manticore.workspace` property, breaking some example scripts. We should reintroduce it as returning `self._output._store.uri`, since it's what the result hook outputs.

**Comment by feliam** [comment]
Alternative. Make the .workspace property return the actual workspace and overload `__str__()` of Workspace to output the uri

**Comment by yan** [comment]
`Workspace` instances are actually properties of the Executor, Manticore just has `ManticoreOutput` that it uses to initialize a workspace. We can:

1) Move workspace to Manticore and access ManticoreOutput implicitly, making `m.workspace` actually return a workspace.
2) Alias `Manticore.workspace` to the `ManticoreOutput` instance and implement its `__str__` method. (This would be super confusing however)
3) Create a `Manticore.output` property and alias it to `ManticoreOutput` (also implementing `__str__`)
