### ISSUE TITLE
Testcase generation at the end of the symbolic execution is performed sequentially

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#685]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Lastest revision (3b796091c257248d671f86aa8abc661613f50834)

### Python version

Python 2.7.13

### Summary of the problem

This issue can be reproduced analyzing an ethereum contract with manticore that produces more than one running state at the end of its symbolic execution. The issue is located in the finalize function:

https://github.com/trailofbits/manticore/blob/master/manticore/ethereum.py#L1215

Manticore will produces the corresponding testcases one by one.

### Expected behavior

I expect manticore to honor the procs parameter (number of workers to use in the exploration) and solve the testcases constrains concurrently.

**Comment by mossberg** [comment]
https://github.com/trailofbits/manticore/pull/697
