### ISSUE TITLE
First class API support for evm

### ISSUE THREAD

**Issue by offlinemark** [trailofbits/manticore#696]
Ethereum support is somewhat hacked onto the side of "regular" manticore right now. Ethereum has first class support in the command line, but not in the API.

To get a feel for this, just look at the imports:

Linux usage: `from manticore import Manticore`
Ethereum usage: `from manticore.ethereum import ManticoreEVM`

a few things just feel wrong about this...

- what is the relationship between `Manticore` and `ManticoreEVM`? 
- Why is there no `ManticoreLinux`?
- Why is there no `from manticore.linux import ...`
- why does Linux support reside at the API top level, but ethereum in a submodule?

it is fairly clear that there is an inequality in terms of the Linux and eth APIs, which doesn't make sense as they are simply two different execution platforms that are logically at the same hierarchy level. there should be some amount of symmetry in the APIs for using each.

this will probably require a fairly radical restructure, that would warrant a minor version bump, to 0.2.0.

### historical notes

how did the linux api get like this? the `Manticore` class was the easiest path forward to make manticore more programmable, and not just a command line tool. it was our first attempt at creating a manticore API, and at this point we should reconsider how much sense this design makes, especially given new requirements for eth support.

how did the eth api get like this? historically, when eth support first started, the eth api was first created in examples/evm/seth.py. that file included `ManticoreEVM`, a `Manticore` subclass implementing a sort of Eth api object. that file was simply moved into the manticore package as manticore/ethereum.py. now that we've successfully gotten ethereum support working at all, we should take some time to think about how to properly fit ethereum support into the codebase such that it has first class api support, and is congruent with Linux.

**Comment by mossberg** [comment]
related: https://github.com/trailofbits/manticore/projects/5#card-6237104, https://github.com/trailofbits/manticore/issues/688

**Comment by feliam** [comment]
We just need to abstract up the states queue/list to Manticore class. Then the fact that evm needs to execute a search after a search (a tx after tx) over all alive states can be implemented via a plugin. 
This can be useful for linux if some kind of symbolic filesystem gets implemented and you want to run one program after the other. Or if execve is implemented (similar to internal tx in evm)
