### ISSUE TITLE
EVM world access refactor

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#725]
Instead of accesing storage[address][balance] from the evm cpu we should maintaina a back reference to the evmworld from the evm-cpu and do a world.get_balance(address)

https://github.com/trailofbits/manticore/blob/master/manticore/platforms/evm.py#L1524
There is already some refactoring in motion.. https://github.com/trailofbits/manticore/blob/master/manticore/platforms/evm.py#L2019-L2020

**Comment by mossberg** [comment]
#843
