### ISSUE TITLE
Improve EVM intruction test

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#727]
Make tests for all intructions  (not just some) https://github.com/trailofbits/manticore/tree/master/tests/EVM 
Add symbolic tests where all the input state is symbolic in different ways.

**Comment by feliam** [comment]
Maybe like this? https://github.com/trailofbits/manticore/blob/59a5ff0ba335d3c0409dbac7dfed3a6a225943bf/tests/eth_general.py#L367-L380

**Comment by disconnect3d** [comment]
Closing this as I believe this is already done with VMTests and will be extended with GeneralStateTests (see #1163).
