### ISSUE TITLE
Support for AArch64

### ISSUE THREAD

**Issue by disconnect3d** [trailofbits/manticore#748]
Hey, any plans for supporting AArch64?

What has to be done to add an arch?

**Comment by mossberg** [comment]
hi @disconnect3d , no plans at the moment unfortunately, but we'd absolutely love to see some external contributions toward that end, which would certainly qualify for bounties.

for adding a new arch, check out some of the existing code in `manticore/core/cpu`. you'll basically need to write a cpu emulator for the arch that handles symbolic data. the ARMv7 cpu in arm.py is probably the most approachable to read. basically you want to implement a subclass for `abstractcpu.py:Cpu`. to do so, you can reuse the `Memory`, and `Register` classes that exist. feel free to ask any and all other questions, as well as ping us the empire hacking slack (link in the readme) for more help!

**Comment by dguido** [comment]
I’m open to offering $10,000 in total bounties for progress towards AArch64 support. Support for this new CPU architecture would go above our standard bounty amounts. Please contact us if you’re planning on starting.

**Comment by catenacyber** [comment]
What is the status of this ? Has anyone started ?

**Comment by yan** [comment]
Hey @catenacyber, that work has been started by @disconnect3d on PR #754. It's been progressing as he finds time to work on it.

**Comment by catenacyber** [comment]
Thanks, so I will look into another issue when I find time myself.

**Comment by ehennenfent** [comment]
#1424
