### ISSUE TITLE
Infrastructure and skeleton classes for aarch64 support

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#753]
This is the tracking issue for the first step in aarch64 support. 

Task: Implement support for aarch64 binary paths as the argument to the Manticore constructor/linux classmethod.

Calling `Manticore(‘aarch64_elf’, [‘arg1’, ‘arg2’], dict(ENV=’env’))` and `Manticore.linux(‘aarch64_elf’, [‘arg1’, ‘arg2], dict(ENV=’env’))` should successfully execute, having loaded the binary and prepared the initial execution State. In this example, ‘aarch64_elf’ is the path to an aarch64 Linux ELF binary.

Completing this will involve modifying files including manticore.py, linux.py, cpufactory.py, and creating a new file in manticore/core/cpu for all the aarch64 code (aarch64.py? Not sure of the best name). The changes will involve modifying mostly the plumbing between components, modifying some logic, and creating new empty, skeleton classes for the Aarch64/Armv8 (naming?) cpu, Armv8 function abi, and Armv8 syscall abi. This task will not involve implementing an ELF loader, just connecting to one that already exists.

Changes that should also be implemented:
- Improve the error message Manticore gives for an unsupported binary arch. Currently KeyError, let’s raise an Exception with a good error message.
- Emit a logger warning that clearly states that Aarch64 support is experimental. This should be clearly visible to all users who pass an aarch64 binary to Manticore.

Please use the #manticore channel in the Empire Hacking slack to communicate with the Manticore development team while completing this task! https://empireslacking.herokuapp.com

**Comment by disconnect3d** [comment]
Hey,

I started some work to make it work properly.

By the way, did you mean that envs should be passed as a keyword argument like this:
```
Manticore(‘aarch64_elf’, [‘arg1’, ‘arg2’], env=dict(ENV=’env’))
```

(when I pass the last arg as `dict(ENV='env')` I get an exception of `Invalid workspace` - I am going to change the message to `Invalid workspace_url` so that it is a bit more verbose :P).

**Comment by mossberg** [comment]
awesome, thanks for starting!

> By the way, did you mean that envs should be passed as a keyword argument like this:

yes, my mistake, sorry 😅 



> I am going to change the message to Invalid workspace_url so that it is a bit more verbose :P).

sounds good 👍 

> should we name it aarch64 or arm64 or maybe armv8 (as we have armv7 for arm x32)?

I am leaning towards `Armv8` to keep consistent with the current `Armv7`. @trailofbits/manticore @yan @feliam any opinions on this?

**Comment by yan** [comment]
Regarding naming, I'd prefer `aarch64` as it's less ambiguous; armv8 is technically a superset of 32bit and 64 bit instructions. If we architect new aarch64 support to cover all armv8 binaries, then calling it `armv8` is appropriate imho.

**Comment by ehennenfent** [comment]
#1424
