### ISSUE TITLE
Feature request: support analysis of smart contracts created using Truffle 

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#768]
It will be nice to support the automatic analysis of ethereum contracts created using the [truffle framework](https://github.com/trufflesuite/truffle). This frame seems to be really popular with more than 52k downloads per month. As an example, you can see [here how mythril deals with it](https://github.com/ConsenSys/mythril/blob/master/mythril/support/truffle.py), just loading the bytecode directly when it is compiled.

**Comment by benjaminmbrown** [comment]
I agree. Would be a huge benefit to include it in a test or build process by default. Will solve a ton of latent issues across the smart contract dev space.

**Comment by mossberg** [comment]
thanks for the feedback @benjaminmbrown! can we dig into this a bit more to more specifically spec out what this feature should look like? what would you like to see?

one idea:  something like extending the manticore cli tool to let you point it at a truffle directory, and automatically do some kind of analysis on the contracts within, with a certain time limit. however, we need to decide on what exactly that "analysis" is. the plain out of the box symbolic transactions might not be that effective..

**Comment by benjaminmbrown** [comment]
@mossberg Would love to help out on both spec out and dev. I will come up with something over the next few days.

**Comment by sneko** [comment]
Any news about that 😀 ?

**Comment by ESultanik** [comment]
Note that Etheno's integration with Manticore is dependent on the [`dev-account-address-provider-m1`](https://github.com/trailofbits/manticore/tree/dev-account-address-provider-m1) branch, so you'll have to make sure you are using that branch until PR #1054 is merged (which will hopefully be very soon). There are instructions on how to do this on the Etheno GitHub page.

**Comment by sneko** [comment]
@ESultanik great thank you! I will give it a try 🌷

**Comment by benjaminmbrown** [comment]
This is awesome @ESultanik . Thanks for putting it together. Will test it out asap.

**Comment by montyly** [comment]
I think this can be closed. Since `crytic-compile` support, Manticore supports Truffle natively
