### ISSUE TITLE
Lack of documentation in the use of terminate and finalize

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#790]
There is no clear documentation on the use of `terminate` and `finalize` in context of the symbolic execution of x86 and ethreum contracts. Maybe a small example using a smart contract in the README can help to clarify this.

**Comment by mossberg** [comment]
I'd say let's include some real documentation in docstrings!

**Comment by mossberg** [comment]
We also actually do document .terminate() http://manticore.readthedocs.io/en/stable/api.html#manticore.Manticore.terminate :)
