### ISSUE TITLE
EVM: STOP instruction returns random values

### ISSUE THREAD

**Issue by montyly** [trailofbits/manticore#792]
### Manticore version
f4118f4f0f0db9ebcb97c08b103b04224bc795ee

### Summary of the problem
The STOP instruction returns an array of random values instead of 0

### Step to reproduce the behavior
```
# contract.sol
pragma solidity ^0.4.20;

contract Test{
    function () payable{
        assembly{
            stop
        }
    }
}
```

$ manticore contract.sol
m.main:INFO: Beginning analysis
m.ethereum:INFO: Starting symbolic transaction: 1
m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 100% | Terminated States: 1 | Alive States: 1
m.ethereum:INFO: Generated testcase No. 0 - STOP
[..]
cat mcore_XXX/test_00000000.tx
[..]

Function call:
{fallback}() -> STOP 
return: ( ... garbage values ...)

### Expected behavior
STOP should return (0,0) (see http://solidity.readthedocs.io/en/develop/assembly.html)

### Actual behavior
STOP returns an array of random values

**Comment by ggrieco-tob** [comment]
Fixed in fbf0823cb61aa7f3b417839a4e2e7e3f58352f10
