### ISSUE TITLE
don't force a potentially unsat dynarg size

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#800]
this is related to #787 and #715 

from @feliam:
> We should ask the solver for a plausible solution instead of forcing/attempting a specific size which may not be feasible.

this is in reference to the code like this in `_concretize_offsets_and_sizes`

```
           concrete_offset_to_arg_data = free_pointer - 4
            state.constrain(offset_to_arg_data == concrete_offset_to_arg_data)
            data[arg_head_element_offset:arg_head_element_offset + 32] = pack32(concrete_offset_to_arg_data)
```

**Comment by disconnect3d** [comment]
This issue is a small edge case in #715 which never landed on master.

I'm closing it for now - this may come up in the future if someone works on similar stuff.
