### ISSUE TITLE
ManticoreEVM.transaction should safely return if there are no running states

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#802]
This is in reference to this comment/diff: https://github.com/trailofbits/manticore/pull/715#discussion_r164883644

That diff which added the `if not self.running_state_ids` to `multi_tx_analysis` was removed from Pr #715 since that was somewhat irrelevant to the dynargs feature. A separate pr should be created to handle this situation in the Manticore core; not the the `multi_tx_analysis` function, which is a very high level function, that is essentially user code. Handling it in the core would mean users of the api that are manually calling `.transaction` would also benefit.

currently we raise an assertion error if there are no running states and no initial state
https://github.com/trailofbits/manticore/blob/master/manticore/ethereum.py#L940

**Comment by mossberg** [comment]
related: https://github.com/trailofbits/manticore/issues/795

**Comment by mossberg** [comment]
we decided that ManticoreEVM.run() should just return if there were no states, but ManticoreEVM.transaction() should actually error. this is because this was actually an error on the user's part, and they should be notified

**Comment by feliam** [comment]
What would be a correct use case for 'm.run()' without alive states? 
Like, When would you do a run() on an empty set and expect no exception?

**Comment by mossberg** [comment]
i guess i'm still not totally sure. is it particularly _incorrect_ to do nothing? what is the job of .run()? process the queue until it's empty?

**Comment by feliam** [comment]
yes. 
Though starting on empty queue may be a bug (on the part of the user) most likely.
