### ISSUE TITLE
Clean up Ethereum exception hierarchy

### ISSUE THREAD

**Issue by yan** [trailofbits/manticore#806]
Currently, Ethereum uses a number of exceptions to implement dispatch on certain behaviors (`Create`, `Return`, `Stop`, etc). `Create` inherits from `Call`, while `Revert` and `Return` both inherit from `EVMInstructionException` directly, while using identical fields for similar purposes (such as data and value).

This issue tracks the effort to refactor the exception code to make the hierarchy and its use more consistent.

**Comment by mossberg** [comment]
addressed with recent EndTx changes
