### ISSUE TITLE
Solidity function name collision

### ISSUE THREAD

**Issue by montyly** [trailofbits/manticore#810]
### Manticore version
https://github.com/trailofbits/manticore/tree/61babdbe21b99c93c74d7ccecbf520108071761a

### Summary of the problem
If two function share the same name but with a different signature, Manticore will not be able to execute of the two functions.

### Step to reproduce the behavior
```python
from manticore.ethereum import ManticoreEVM
from manticore.core.smtlib import Operators, solver

m = ManticoreEVM() # initiate the blockchain
source_code = '''
contract Test{

    function ret(uint) returns(uint){
        return 1;
    }

    function ret(uint, uint) returns(uint){
        return 2;
    }
}
'''

# Generate the accounts
user_account = m.create_account(balance=1000)
contract_account = m.solidity_create_contract(source_code, owner=user_account)

# Try to execute ret(uint), but instead Manticore executes ret(uint,uint) 
contract_account.ret(m.SValue)

print m.workspace

m.finalize()
```

`mcore_XXXX/test_00000000.tx` will then contain:
```
Function call:
ret(0,0) -> RETURN (*)
return: 2 
```

### Expected behavior
The execution of `ret(uint)`. 
`test_00000000.tx` should contain:
```
Function call:
ret(0) -> RETURN (*)
return: 1
```

### Actual behavior
The execution of `ret(uint, uint)`

**Comment by feliam** [comment]
Go low level. Use something like this
```
m.transaction(caller=user_account,
              address=contract_account,
              data=ABI.make_function_call("ret(uint)", m.SValue),
              value=m.SValue )

```

Will this happen again if the signature of ret is changed but maintaining the arguments count ? ret(uint, address) is a different version that ret(uint, uint)

We can:
* Print a warning when using the solidity helper ABI (account.function_name(..)) and there is more then 1 candidate in the metadata.
* select known signatures by name AND ALSO by argument count (still potential collision)
* warm also when some python-ish name is used in the solidity contract 

Note that there will ever be functions that would not be callable from the python account object:  
```
     function __init__(uint, address) returns(uint){
        return 2;
    }
```

**Comment by defunctio** [comment]
Just checked this against the current master; https://github.com/trailofbits/manticore/commit/b1a09d2ddc918e7e8960647d2e4899cd1835cb10  

```
    raise EthereumError("A function with that name is already defined")
manticore.ethereum.EthereumError: A function with that name is already defined
```
As is we are unable to analyze any solidity code that uses overloaded functions? This seems worse than the previous behavior or was there another reason?

**Comment by feliam** [comment]
Hmm... yes I guess we should detect the exception from our internal code and delete all instances of "ret"(reused name) so the user wont use the wrong one by mistake?

**Comment by defunctio** [comment]
That sounds like a reasonable solution. We should probably document the new behavior and correct way to call overloaded functions somewhere too.

**Comment by feliam** [comment]
I'm thinking that having this redundant metadata helps when generating the report at the end. 
Another idea is to keep all the metadata we can but then check for repetitions at EVMContract class/object magic. 
If there are repetitions we have then 2 options:
* Try to disambiguate using the number of arguments, and raise if fail?
* Just raise

**Comment by defunctio** [comment]
I think it makes the most sense to raise with a more descriptive exception when referencing overloaded functions through `__getattribute__`  rather than attempting any type of automatic resolution. 

Maybe for convenience the wrapped function `f` could respect a `signature` kwarg that assists in call resolution when overloaded? 

Something like; `m.overloaded_method(..., signature='(uint, uint)')` or similar?
