### ISSUE TITLE
ManticoreEVM.finalize() requires to use solidity source code

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#842]
The function ManticoreEVM.finalize() required to terminate live states and generate input cases, fails if we do not have the source code of a contract. This function uses solidity metadata to calculate code coverage [here](https://github.com/trailofbits/manticore/blob/master/manticore/ethereum.py#L1360).

**Comment by mossberg** [comment]
i believe this is addressed now
