### ISSUE TITLE
--txaccount option

### ISSUE THREAD

**Issue by rmi7** [trailofbits/manticore#845]
[This trailofbits](https://blog.trailofbits.com/2018/03/23/use-our-suite-of-ethereum-security-tools/) post talks about a manticore `--txaccount` option, but manticore tells me this option does not exist.

**Comment by ggrieco-tob** [comment]
Are you using the last git revision?

**Comment by rmi7** [comment]
I am using pip to install manticore, will try using git repo. thanks!

**Comment by dguido** [comment]
I think it's only in master! We'll release a new version via pip soon.
