### ISSUE TITLE
Pin solc supported versions

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#846]
Detect installed solc version and print a warning when unsupported.
The output format of solc varies a bit among versions and breaks mcore slightly.
related to https://github.com/trailofbits/manticore/issues/844

**Comment by montyly** [comment]
I think this can be closed, now that manticore uses `crytic-compile`

**Comment by ehennenfent** [comment]
Agreed. We briefly had this from #1488 but it proved to be burdensome.
