### ISSUE TITLE
EXTCODESIZE gas cost adjustment in EIP 150

### ISSUE THREAD

**Issue by taxic** [trailofbits/manticore#858]
https://github.com/trailofbits/manticore/blob/c6f457d72e1164c4c8c6d0256fe9b8b765d2cb24/manticore/platforms/evm.py#L626
change 20 to 700

**Comment by mossberg** [comment]
thanks @taxic! so i'm not super familiar with this stuff; if we changed 20 to 700, but then wanted to analyze a contract the was deployed before EIP 150 took effect, would 700 be incorrect to use for that analysis?

**Comment by taxic** [comment]
According to [eip-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md), 
if we analyze a transaction happened before block height 2,463,000, 700 is wrong for calculating gas cost. It doesn't depend on contract creation block, but depends on block number where transactions are included.

Hard-forks make things complicated.
