### ISSUE TITLE
Add Support for Solidity Contracts Using Libraries

### ISSUE THREAD

**Issue by lts-rad** [trailofbits/manticore#864]
### OS / Environment
N/A
### Manticore version
0.1.8

### Python version
2.7

### Dependencies
N/A

### Summary of the problem
Manticore is currently unaware of contracts with libraries. The solidity compiler also does not appear to have a flag to inline the library code. Although it is understood that Manticore is currently designed to only analyse one contract at a time, perhaps there is a reasonable way to work with contracts that are dependent on libraries.  Another approach might be to find or write a tool that can do a source-code transformation for code that uses libraries.

### Step to reproduce the behavior
N/A

### Expected behavior
N/A

### Actual behavior
Trying to run manticore on a contract dependant on libraries results in an error when decoding that contract's bytecode, which contains the placeholders for the library addresses. 

https://github.com/trailofbits/manticore/blob/master/manticore/ethereum.py#L701

### Any relevant logs
N/A

**Comment by lts-rad** [comment]
Thank you!! Also thanks for clarifying my misunderstanding on multi-contract support.

**Comment by mossberg** [comment]
i believe this is addressed in #843 , will close
