### ISSUE TITLE
github install instructions do not require solc compiler

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#868]
Clarify instructions so it mention the optional dependency on solc
'''
# Install system dependencies
sudo apt-get update && sudo apt-get install python-pip -y

# Install manticore and its dependencies
sudo pip2 install manticore
'''

**Comment by mossberg** [comment]
That's from the quick start instructions, the readme does clearly state the solc dependency:

> Ethereum smart contract analysis requires the solc program in your $PATH.

https://github.com/trailofbits/manticore/blob/aa792588fe3a883276ea30ba543ec8822cf44db0/README.md#requirements

**Comment by Martin2877** [comment]
how to install solc and add it to $PATH?

**Comment by Martin2877** [comment]
I fix it after:
`sudo add-apt-repository ppa:ethereum/ethereum

sudo apt-get update

sudo apt-get install solc`
