### ISSUE TITLE
Add support for installing manticore with newest capstone

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#881]
Some "bugs" in Manticore are actually just bugs in capstone (e.g. #560). We've historically just added various hacks in the codebase to hack around these bugs (e.g. #852), since there is no pypi release for newer capstone versions where these are fixed (v4+).

We should investigate using the setup.py dependency links feature to allow users to install a capstone version from a github link (see https://github.com/trailofbits/manticore/pull/852#pullrequestreview-108970169) if they opt in using the `--process-dependency-links`. the desired behavior

- if a user does `pip install manticore` they get manticore installed with latest capstone on pypi
- if a user does `pip install --process-dependency-links manticore` they get manticore installed with the latest capstone `next` branch 

help would be greatly appreciated with this!

what needs to be done:
- something along the lines of setup.py should be modified to use the dependnecy links feature linking to https://github.com/aquynh/capstone/archive/next.zip#subdirectory=bindings/python
- test installing via `pip install .` -> confirm the capstone version is 3.0.5rc2
- test installing via `pip install --process-dependency-links .` -> confirm the capstone version is 4+
- modify the readme to document that the `--process-dependency-links` argument may be used by binary analysis users who are experiencing error and unexpected "invalid memory access" testcases

--

thanks to @disconnect3d for the suggestion!

**Comment by mossberg** [comment]
re #852

**Comment by ggrieco-tob** [comment]
Another option is to fork the capstone repository and make manticore to use that repository URL to install recent snapshots of it. We should update sync it with upstream from time to time.
