### ISSUE TITLE
Implement SMT optimizations

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#89]

**Comment by yan** [comment]
Implement optimizations described here: https://github.com/trailofbits/0ff5737e0351543507f9485119260ab6/blob/master/_posts/2017-02-27-Regarding-SE-Optimizations.markdown

**Comment by yan** [comment]
This issue tracks SMT optimizations, which have been a known issue for a while. Closing this because: we're aware of this, and this specific issue was light on details.
