### ISSUE TITLE
CTRL+C fails to exit clean

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#903]
Keyboard interruption fails close everything and call finalize. To trigger just try to cancel (CTRL+C) default evm analysis a few times.

**Comment by disconnect3d** [comment]
Loud thinking: since we save a lot of state anyway it would be nice to be able to suspend analysis/processing with ctrl+c and resume it later (so one could e.g. restart computer or move state to another machine).

**Comment by feliam** [comment]
Yes! We used to have the ability to start from a previously canceled "workspace". Which pretty much has only a bunch of serialized states.
It's a nice idea. I think that we'll need the config(*) idea first so the analysis is actually continuable.

config: (I think it may be an issue already for this)
Need a global accessible configuration module backed by 3 things:
* A default value
* A .ini file (https://docs.python.org/3/library/configparser.html) that will end up in the workspace folder
* Commandline arguments

eg.
config.smtlib.assume_unknown_as_unsat
config.smtlib.solver_timeout
config.global.random_seed ?
...

**Comment by ehennenfent** [comment]
https://github.com/trailofbits/manticore/wiki/Ideas
