### ISSUE TITLE
Integrate linter into CI

### ISSUE THREAD

**Issue by offlinemark** [trailofbits/manticore#91]

**Comment by mossberg** [comment]
We should still do this at some point. One problem, is that typically the list of issues it outputs is immense, and we don't particularly care to eliminate all of them. A solution could be to, on each commit, only output the diff between the last lint output, and the current

**Comment by mossberg** [comment]
In particular, and at the very least, I'm interesting in using them to help us check that our docstrings are consistent with the actual functions. i think they can do this
