### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by lambdax01** [trailofbits/manticore#964]
### OS / Environment
mac os 10.13.5

### Python version
2.7.10

### Dependencies
altgraph==0.10.2
bdist-mpkg==0.5.0
bonjour-py==0.3
capstone==3.0.5rc2
cytoolz==0.9.0.1
eth-hash==0.1.4
eth-utils==1.0.3
functools32==3.2.3.post2
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
ply==3.11
py2app==0.7.3
pyelftools==0.24
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
pysha3==1.0.2
python-dateutil==1.5
pytz==2013.7
rlp==1.0.1
scipy==0.13.0b1
six==1.4.1
toolz==0.9.0
unicorn==1.0.1
xattr==0.6.4
zope.interface==4.1.1

### Summary of the problem
installation fails with following error
copying bin/z3 -> /System/Library/Frameworks/Python.framework/Versions/2.7/bin
    error: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/bin/z3'

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-yqdyCU/z3-solver/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-_TMOBC/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-yqdyCU/z3-solver/

### Step to reproduce the behavior
sudo pip2 install manticore

**Comment by ggrieco-tob** [comment]
Can you try using `pip2 install manticore --user`

**Comment by lambdax01** [comment]
Fixed it. Thanks
