### ISSUE TITLE
AttributeError: 'ManticoreEVM' object has no attribute 'SByte' 

### ISSUE THREAD

**Issue by fuying95** [trailofbits/manticore#967]
### OS / Environment

Ubuntu 16.04

### Manticore version

manticore 0.1.10 installed from pip

### Python version

Python 2.7.12

### Summary of the problem
I installed the manticore followed readme, and successfully run linux/basic example.

But I failed to run /manticore/examples/evm/coverage.py & /manticore/examples/evm/reentrancy_symbolic.py & /manticore/examples/evm/simple_mapping.py, the error message: "AttributeError: 'ManticoreEVM' object has no attribute 'SByte' "

Is it my installation problem? Thanks for your help!

**Comment by feliam** [comment]
We need to update the examples and document the last few ethereum API changes.

You probably did everything okay. We are faster writing new features and improvements than documenting them though. SByte/SValue are deprecated in favor of m.make_symbolic_value and m.make_symbolic_buffer(). 

https://github.com/trailofbits/manticore/blob/yolo_master/examples/evm/minimal.py

```
git clone git@github.com:trailofbits/manticore.git
cd manticore
git checkout yolo_master
python setup.py develop --user
```

**Comment by fuying95** [comment]
Thank you!
