### ISSUE TITLE
AttributeError: 'ConstraintSet' object has no attribute 'constraint'

### ISSUE THREAD

**Issue by evanpjensen** [trailofbits/manticore#976]
### OS / Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

### Manticore version
61270a2  

### Python version
Python 2.7.15rc1

### Summary of the problem
Type error, AttributeError: 'ConstraintSet' object has no attribute 'constraint' at https://github.com/trailofbits/manticore/blob/master/manticore/ethereum.py#L1621

### Step to reproduce the behavior
execute bug.py
[bug.zip](https://github.com/trailofbits/manticore/files/2194574/bug.zip)

### Expected behavior
No crash

### Actual behavior
Crash

### Any relevant logs
Line numbers may be slightly off
```
Traceback (most recent call last):
  File "bug.py", line 24, in <module>
    contract_account.f(caller=user_account)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/ethereum.py", line 981, in f
    data=tx_data)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/ethereum.py", line 1541, in transaction
    self._transaction('CALL', caller, value=value, address=address, data=data)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/ethereum.py", line 1697, in _transaction
    _, caller, address, value, data = self.__migrate_expressions(state.constraints, self.constraints, caller, address, value, data)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/ethereum.py", line 1624, in __migrate_expressions
    new_constraints.constraint(new_constraints.migrate(c, bindings=migration_bindings))
AttributeError: 'ConstraintSet' object has no attribute 'constraint'

```

**Comment by feliam** [comment]
Thanks! I think this is a known bug. And that it is solved on our develop branch `yolo_master` :)  I'll check check soon.

Send more!

**Comment by evanpjensen** [comment]
add an m.finalize() at the end to trigger a type error in z3 Exception: Error in smtlib: (error "line 266 column 24: operator is applied to arguments of the wrong sort") in `yolo_master`


[bug.zip](https://github.com/trailofbits/manticore/files/2194604/bug.zip)

**Comment by mossberg** [comment]
looks like this runs fine on dd66de448e620acb1c83817c3123bd5c8e442734, will close
