### ISSUE TITLE
Refactor: move ConcretizeRegister/ConcretizeMemory elsewhere

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#987]
"ConcretizeRegister/ConcretizeMemory" is platform specific (as in it wont work for EVM) so it should go to ._platform.execute not state.py/State.execute()

**Comment by yeti-detective** [comment]
@feliam It looks like [PR 1257](https://github.com/trailofbits/manticore/pull/1257) moved  ConcretizeRegister/ConcretizeMemory from `manticore/core/state.py` to `manticore/native/state.py` which I think might have solved this issue.
It wouldn't be part of `._platform.execute` but it would no longer be available to the Ethereum platform either.
If this still needs more work, I wouldn't mind taking a whack at it.

**Comment by feliam** [comment]
Yes I think this particular issue was solved.  There was a big refactor separating the native from the evm waterss. Closing this. Do not worry there is plenty of other entry points. If you can not find it in the issue stack please join us at https://empireslacking.herokuapp.com/ #manticore
